/**
 * Jahrom Language System — v3
 * EN / AR / UR / FA / HI
 * RTL: AR, UR, FA | LTR: EN, HI
 */

const JUHRUM_LANGS = {
  en: {
    dir: 'ltr', font: null, label: 'EN',
    t: {
      nav_home: 'Home',
      nav_products: 'Products',
      nav_story: 'Our Story',
      nav_contact: 'Contact',
      nav_whatsapp: 'WhatsApp Us',
      pl_step1: 'Calibrating...',
      pl_step2: 'Building...',
      pl_step3: 'Ready.',
      pl_sub: 'Desert Iron — Est. 2004 — Sharjah UAE',
      hero_tag: 'Sharjah, UAE — Industrial Area 4 — Est. 2004',
      hero_l0: 'DESERT',
      hero_l1: 'IRON.',
      hero_l2: 'BUILT.',
      hero_sub: 'Built for drivers who don\'t compromise. Over 22 years. 500+ builds. Every truck hand-fitted in Sharjah\'s Industrial Area 4.',
      hero_btn_products: 'View Products',
      hero_btn_story: 'Our Story',
      stat_years: 'Years Experience',
      stat_rating: 'Google Rating',
      stat_trucks: 'Trucks Built',
      scroll_lbl: 'Scroll to Explore',
      tick1: 'Bed Covers',
      tick2: 'Exterior Builds',
      tick3: 'Audio Systems',
      tick4: 'Paint Protection',
      tick5: 'Upholstery',
      tick6: '4.7★ Google Rating',
      tick7: 'Sharjah UAE',
      ts_tag: 'Product Showcase',
      ts_sub: 'Scroll to explore',
      ts_loading: 'Loading',
      ts_p0_title: 'The Base Build',
      ts_p0_desc: 'Every Jahrom build starts with the stock truck — a blank canvas. We assess the vehicle, plan the build, and source every accessory to spec. Nothing gets fitted that doesn\'t belong.',
      ts_p0_hint: '↓ Keep scrolling',
      ts_p1_title: 'Full Safari Build',
      ts_p1_desc: 'Lights on. Accessories locked in. This is the complete Jahrom treatment — every exterior mod fitted flush, every light dialled in. Built for the UAE desert and beyond.',
      ts_p1_note: 'Exterior builds from AED 8,000',
      ts_p2_title: 'Power Side Step',
      ts_p2_desc: 'Electric retractable side steps that deploy the moment you open the door. Precision-fitted to your truck\'s sill, flush when closed, solid underfoot when extended. No rattle. No gap.',
      ts_p2_note: 'Steps from AED 2,200 fitted',
      ts_p3_title: 'Tri-Fold Bed Cover',
      ts_p3_desc: 'Hard tri-fold tonneau covers that lock your bed down. Weatherproof, low-profile, and strong enough to stand on. Opens fully in seconds, locks tight for highway speeds.',
      ts_p3_note: 'Bed covers from AED 3,400 fitted',
      ts_p4_title: 'Front Grille',
      ts_p4_desc: 'Custom billet and mesh grilles that transform the face of the truck. Every grille is fitted with OEM precision — no drilling, no gaps, no flex. Your truck\'s most visible statement.',
      ts_p4_note: 'Grilles from AED 1,800 fitted',
      ts_p5_title: 'See the Full Catalogue',
      ts_p5_desc: 'Roof racks, snorkels, winches, lighting rigs, PPF, audio builds — the full Jahrom range. Every accessory sourced, every fitment guaranteed.',
      ts_p5_btn: 'View Full Catalogue',
      ts_hint_text: 'Scroll to Build',
      ts_hint_sub: 'Keep scrolling for 3D interactive showcase',
      booking_h3_l1: 'YOUR TRUCK.',
      booking_h3_l2: 'YOUR TERMS.',
      booking_text: 'No waiting lists. No upselling. Tell us your truck, we\'ll tell you exactly what fits, what it costs, and when it\'s done.',
      booking_btn_wa: 'WhatsApp Us',
      booking_btn_call: 'Call: 050 300 2898',
      booking_info: 'Open Sat–Thu: 8AM–11PM, Fri: 3PM–11PM',
      story_section_tag: 'Our Journey',
      story_section_h2_l1: 'FROM VISION TO',
      story_section_h2_l2: 'REALITY',
      stage1_tag: 'The Origin — 01 / 04',
      stage1_title: 'Foundation',
      stage1_text: 'Industrial Area 4. 2004. One rule: serious trucks deserve serious gear. Everything else is negotiable.',
      stage2_tag: 'The Method — 02 / 04',
      stage2_title: 'Craft',
      stage2_text: 'No templates. No rush jobs. Every fit verified twice. Your Silverado isn\'t our last Silverado — it\'s the only one that matters.',
      stage3_tag: 'The Proof — 03 / 04',
      stage3_title: 'Trusted',
      stage3_text: '4.7★ didn\'t come from marketing. It came from 500+ trucks that still look factory-fresh in UAE heat. Word travels.',
      stage4_tag: 'The Present — 04 / 04',
      stage4_title: 'Today',
      stage4_text: 'Ram TRX. F-150 Raptor. GMC Sierra Denali. Built them all. Your truck\'s next chapter starts in Industrial Area 4.',
      reviews_h2_l1: 'WHAT THEY',
      reviews_h2_l2: 'SAY.',
      rating_label: 'Google Reviews',
      r1_text: '"Best shop for 4x4 accessories in Sharjah. They know their trucks — Tundra, GMC, Ram, F-150. Prices are honest and the team actually knows what they\'re doing."',
      r1_name: 'Adnan Aadi',
      r1_meta: '6 months ago',
      r2_text: '"Got a rear hitch carrier fitted same day. Fair prices, no nonsense. Good stock of offroad parts that you won\'t find elsewhere in Sharjah."',
      r2_name: 'Hisham Irshad',
      r2_meta: '2 months ago',
      r3_text: '"Professional team. Quality work. Every detail on my truck was handled properly — not rushed, not cut short. Highly recommended."',
      r3_name: 'Mohammed R.',
      r3_meta: '4 months ago',
      cs_whatsapp_label: 'WhatsApp — Fastest Response',
      cs_whatsapp_val: 'Message Us Now',
      cs_call_label: 'Call Direct',
      cs_call_val: '050 300 2898',
      cs_visit_label: 'Walk In — No Appointment',
      cs_visit_val: 'Industrial Area 4, Sharjah',
      footer_tag: 'Desert Iron — Built for Power',
      footer_copy: '© 2025 Jahrom Auto Accessories, Sharjah UAE',
      contact_hero_tag: 'Get In Touch',
      contact_hero_h1_l1: 'COME IN.',
      contact_hero_h1_l2: 'BUILD IT.',
      contact_hero_sub: 'No appointment needed. Walk in, tell us about your truck, and we\'ll show you what\'s possible.',
      contact_btn_wa: 'Message on WhatsApp',
      contact_btn_call: 'Call: 050 300 2898',
      contact_email: 'h_jahrom@yahoo.com',
      contact_social_title: 'See the builds. Follow us.',
      contact_instagram: 'Instagram',
      contact_youtube: 'YouTube',
      contact_tiktok: 'TikTok',
      story_page_hero_sub: 'Expert craftsmanship. UAE desert. Over 22 years of building the best pickup trucks in Sharjah.',
      story_ch1_title: 'The Origin',
      story_ch1_h2_l1: 'BUILT IN',
      story_ch1_h2_l2: 'SHARJAH.',
      story_ch1_h2_l3: 'RAISED ON',
      story_ch1_h2_l4: 'IRON.',
      story_ch1_b1: 'Founded over two decades ago in the heart of Sharjah, Jahrom was built on a single belief: that every truck deserves expert-level attention and precision craftsmanship. What started as a specialist workshop became the UAE\'s most trusted pickup truck accessories destination.',
      story_ch1_b2: 'When Hadi established the shop in Sharjah\'s Industrial Area 4, he brought a deep passion for detail with him. He knew exactly what serious truck owners wanted — not just parts, but accessories that genuinely elevated their vehicle. Products chosen with care, fitted with precision, backed with knowledge.',
      story_ch1_b3: 'Over 22 years later, Jahrom has become the go-to destination for pickup truck owners across the UAE who refuse to compromise.',
      story_ch2_title: 'The Environment',
      story_ch2_h2_l1: 'BUILT FOR',
      story_ch2_h2_l2: 'UAE',
      story_ch2_h2_l3: 'TERRAIN.',
      story_ch2_b1: '48°C summers. Sand in every seal. UV that destroys cheap coatings within months. The UAE is one of the most punishing environments on earth for truck accessories — and most shops ignore that.',
      story_ch2_b2: 'We don\'t. Every product at Jahrom has been tested against this climate — not in a lab, but in the real heat of Sharjah summers. Bed covers that lock out desert dust. PPF that doesn\'t yellow. Thermal insulation that actually works.',
      story_ch2_b3: 'If it can\'t handle a full UAE year, it doesn\'t earn a place in our showroom. Full stop.',
      story_ch3_title: 'The Products',
      story_ch3_h2_l1: 'WHAT WE',
      story_ch3_h2_l2: 'ACTUALLY',
      story_ch3_h2_l3: 'DO.',
      story_ch3_b1: 'Ram TRX. F-150 Raptor. GMC Sierra Denali. We\'ve built them all. Jahrom specialises in American pickup trucks — the trucks UAE drivers actually choose when they refuse to compromise.',
      story_ch3_b2: 'Bed covers — from retractable hardtops to soft tri-fold covers. Exterior builds — bull bars, running boards, roof racks. Protection — self-healing PPF. Interior — full leather seat and floor installations in any colour.',
      story_ch3_b3: 'And because we source directly from manufacturers, our prices remain competitive without compromising on quality. That\'s the promise Hadi made when he opened the doors — and it\'s the promise Jahrom keeps every day.',
      story_ch3_cta: 'Browse Products',
      val1_title: 'Precision Fit',
      val1_body: 'Every accessory sourced specifically for American pickup trucks. We know every model, every spec, every year. Perfect fitment every time.',
      val2_title: 'Fair Pricing',
      val2_body: 'Direct supplier relationships mean we eliminate the middleman. Premium quality at prices that don\'t make you choose between good gear and a fair deal.',
      val3_title: 'Professional Installation',
      val3_body: 'We don\'t just sell — we fit. Every product installed by our technical team to factory-finish standard.',
      val4_title: 'UAE-Proven',
      val4_body: 'Over 22 years of UAE desert, heat, and sand have tested every product we stock. If it\'s in our showroom, it earned its place.',
      val5_title: 'Expert Guidance',
      val5_body: 'Not sure what you need? Come in and talk to us — we\'ll recommend exactly what fits your truck, your driving, and your budget.',
      val6_title: 'Word of Mouth',
      val6_body: 'Our reputation has been built entirely by customers who came back, and customers who sent their friends.'
,
      prod_hero_h1: 'Truck Accessories &amp; Builds',
      prod_hero_sub: 'Sharjah UAE — Industrial Area 4',
      prod_tag: 'Browse Products',
      filter_all: 'All',
      filter_beds: 'Bed Covers',
      filter_exterior: 'Exterior',
      filter_interior: 'Interior',
      filter_protection: 'Protection',
      filter_custom: 'Custom',
      prod_1_name: 'Hardtop Retractable',
      prod_1_spec: 'Aerospace-grade 6063-T5 aluminium. Powder-coated matte black. Tested to 500 lb static load. EPDM weather seals keep UAE dust out. Fits F-150, Ram 1500/2500, Sierra. Lock it, load it, forget it.',
      prod_2_name: 'Soft Tri-Fold',
      prod_2_spec: 'Heavy-duty UV-resistant vinyl. Clamp-on fit — zero drilling, zero damage. Folds open in seconds. Fits F-Series, Ram, Tundra. Lightweight protection that actually works in desert heat.',
      prod_3_name: 'Bull Bars',
      prod_3_spec: 'Mild steel and stainless variants. Powder-coated black or polished. Integrated LED mount points. Direct bolt-on for F-150, Ram, Sierra, Silverado. Built for wadi approaches, not car parks.',
      prod_4_name: 'Running Boards',
      prod_4_spec: 'Aluminium and steel. Power retractable options available. Drop steps for lifted trucks. Non-slip surface, direct bolt-on — no cutting required. Ford, Dodge, GMC.',
      prod_5_name: 'Roof Racks',
      prod_5_spec: 'Cab-mounted and full-length systems. Powder-coated steel rated to 150 kg. LED light bar channels built in. Model-specific brackets — overland-ready from day one.',
      prod_6_name: 'Roll Bars',
      prod_6_spec: 'Heavy-duty steel roll bars that define the back of the truck. Powder-coated black with integrated LED light bars and amber accent strip lighting. Direct bolt-on for F-150, Ram, GMC Sierra, Tundra.',
      prod_7_name: 'Floor Leather & Mats',
      prod_7_spec: 'Full floor leather installation in all colours. Heavy-duty all-weather mats with model-specific fit. Anti-slip backing. Covers front, rear, and cargo area. UAE desert-proof.',
      prod_8_name: 'PPF & Paint Protection',
      prod_8_spec: 'Self-healing paint protection film. Full front-end, bonnet, full-body options. Clear and matte finishes. Protects against stone chips, scratches, UV fade.',
      prod_9_name: 'Hardtop Canopy',
      prod_9_spec: 'Full hardshell canopy that turns your truck bed into a weatherproof, lockable cargo space. Fibreglass construction, colour-matched. Integrated windows, interior LED lighting, flush rear lock.',
      prod_10_name: 'Concealed Protection',
      prod_10_spec: 'Concealed paint protection for high-impact areas — door edges, rockers, wheel arches. Invisible application. Protects resale value. Pairs perfectly with PPF.',
      prod_11_name: 'Full Custom Builds',
      prod_11_spec: 'Have a vision? We source, spec, and install to your exact requirements. From single accessories to complete truck transformations — talk to our team.',
      pcard_cta: 'Request Price →',
      pcard_cta_custom: 'Let\'s Talk →',
      dont_see_h: 'DON\'T SEE',
      dont_see_h2: 'WHAT YOU NEED?',
      contact_hours_title: 'HOURS & VISIT',
      contact_reach: 'REACH',
      contact_out: 'OUT.',
      contact_wa_desc: 'WhatsApp is fastest. Send your truck model and what you\'re after — we\'ll come back with options and pricing, usually within the hour. No forms, no waiting lists.',
      contact_find_us: 'FIND US.',
      contact_address: '330 First Industrial St, Industrial Area 4, Sharjah UAE',
      cs_whatsapp_label: 'WhatsApp — Fastest Response',
      cs_call_label: 'Call Direct',
      cs_visit_label: 'Walk In — No Appointment',
      cs_visit_val: 'Industrial Area 4, Sharjah'
    }
  },
  ar: {
    dir: 'rtl', font: 'Noto Sans Arabic', label: 'عربي',
    t: {
      dir: 'rtl',
      font: 'Noto Sans Arabic',
      label: 'عربي',
      nav_home: 'الرئيسية',
      nav_products: 'المنتجات',
      nav_story: 'قصتنا',
      nav_contact: 'تواصل معنا',
      nav_whatsapp: 'واتساب',
      pl_step1: 'جارٍ التحميل...',
      pl_step2: 'لحظة...',
      pl_step3: 'جاهز.',
      pl_sub: 'حديد الصحراء — منذ 2004 — الشارقة',
      hero_tag: 'الشارقة، الإمارات — المنطقة الصناعية 4 — تأسس 2004',
      hero_l0: 'حديد',
      hero_l1: 'الصحراء.',
      hero_l2: 'مُصنَّع.',
      hero_sub: 'للسائق الذي لا يقبل المساومة. أكثر من 22 عاماً. 500+ سيارة مُجهَّزة. كل شيء يتم بأيدي متخصصة في المنطقة الصناعية 4 بالشارقة.',
      hero_btn_products: 'تصفّح المنتجات',
      hero_btn_story: 'قصتنا',
      stat_years: 'سنة خبرة',
      stat_rating: 'تقييم جوجل',
      stat_trucks: 'تجهيز شاحنات',
      scroll_lbl: 'مرّر للاستكشاف',
      tick1: 'أغطية الصندوق',
      tick2: 'تعديلات خارجية',
      tick3: 'أنظمة صوتية',
      tick4: 'حماية الطلاء',
      tick5: 'تفصيل داخلي',
      tick6: '4.7★ تقييم جوجل',
      tick7: 'الشارقة، الإمارات',
      ts_tag: 'عرض المنتجات',
      ts_sub: 'مرّر للاستكشاف',
      ts_loading: 'جارٍ التحميل',
      ts_p0_title: 'البناء الأساسي',
      ts_p0_desc: 'كل سيارة تبدأ من الصفر — نُقيِّم، نخطط، ونختار كل قطعة بعناية. لا شيء يُركَّب دون سبب.',
      ts_p0_hint: '↓ استمر في التمرير',
      ts_p1_title: 'تجهيز سفاري كامل',
      ts_p1_desc: 'إضاءة، إكسسوارات، وأداء متكامل. هذا هو التجهيز الكامل من جهروم — كل قطعة خارجية مثبّتة بدقة، كل إضاءة مُعايَرة. مُصمَّم لصحراء الإمارات وما بعدها.',
      ts_p1_note: 'التجهيزات الخارجية تبدأ من 8,000 درهم',
      ts_p2_title: 'درجة جانبية كهربائية',
      ts_p2_desc: 'درجات جانبية كهربائية تنسحب فور فتح الباب. مثبّتة بدقة على عتبة سيارتك، مخفية عند الإغلاق، متينة عند الاستخدام. بلا اهتزاز ولا فجوات.',
      ts_p2_note: 'الدرجات الجانبية تبدأ من 2,200 درهم مع التركيب',
      ts_p3_title: 'غطاء صندوق ثلاثي الطي',
      ts_p3_desc: 'أغطية صلبة ثلاثية الطي تحمي صندوق شاحنتك. مقاومة للماء، منخفضة المستوى، وقوية. تُفتح بالكامل في ثوانٍ وتُغلَق بإحكام.',
      ts_p3_note: 'الأغطية تبدأ من 3,400 درهم مع التركيب',
      ts_p4_title: 'شبكة مقدمة مخصصة',
      ts_p4_desc: 'شبكات مقدمة مخصصة تُغيِّر ملامح شاحنتك. كل واحدة مُركَّبة بدقة — بدون حفر، بدون فجوات، بدون اهتزاز.',
      ts_p4_note: 'الشبكات تبدأ من 1,800 درهم مع التركيب',
      ts_p5_title: 'اكتشف الكتالوج الكامل',
      ts_p5_desc: 'رفوف السقف، الشنوركل، الونشات، أنظمة الإضاءة، حماية الطلاء، أنظمة صوتية — الكتالوج الكامل لجهروم. كل قطعة بأصالة، كل تركيب مضمون.',
      ts_p5_btn: 'عرض الكتالوج الكامل',
      ts_hint_text: 'مرّر للبناء',
      ts_hint_sub: 'استمر بالتمرير للعرض التفاعلي ثلاثي الأبعاد',
      booking_h3_l1: 'سيارتك.',
      booking_h3_l2: 'بشروطك.',
      booking_text: 'بلا قوائم انتظار. بلا مبالغة في البيع. أخبرنا بموديل سيارتك وسنخبرك بما يناسبها والسعر الدقيق ووقت الانتهاء.',
      booking_btn_wa: 'واتساب',
      booking_btn_call: 'اتصل: 050 300 2898',
      booking_info: 'السبت–الخميس: 8ص–11م، الجمعة: 3م–11م',
      story_section_tag: 'مسيرتنا',
      story_section_h2_l1: 'من الفكرة إلى',
      story_section_h2_l2: 'الواقع',
      stage1_tag: 'البداية — 01 / 04',
      stage1_title: 'التأسيس',
      stage1_text: 'المنطقة الصناعية 4. 2004. قاعدة واحدة: الشاحنات الجادة تستحق معدات جادة. وكل ما عدا ذلك قابل للتفاوض.',
      stage2_tag: 'الأسلوب — 02 / 04',
      stage2_title: 'الحرفة',
      stage2_text: 'لا قوالب جاهزة. لا أعمال متسرعة. كل تركيب يُتحقق منه مرتين. سيارتك ليست آخر سيارة نُجهِّزها — لكنها الوحيدة التي تهم.',
      stage3_tag: 'الإثبات — 03 / 04',
      stage3_title: 'الثقة',
      stage3_text: 'تقييم 4.7★ لم يأتِ من حملات تسويقية. جاء من أكثر من 500 شاحنة لا تزال تبدو كما خرجت من المصنع في حرارة الإمارات. الكلمة تنتشر.',
      stage4_tag: 'الحاضر — 04 / 04',
      stage4_title: 'اليوم',
      stage4_text: 'رام TRX. F-150 رابتور. GMC سييرا دينالي. بنيناها جميعاً. قصة شاحنتك القادمة تبدأ في المنطقة الصناعية 4.',
      reviews_h2_l1: 'ماذا يقول',
      reviews_h2_l2: 'عملاؤنا.',
      rating_label: 'تقييمات جوجل',
      r1_text: '«أفضل متجر لإكسسوارات الدفع الرباعي في الشارقة. يعرفون شاحناتهم — تندرا، GMC، رام، F-150. الأسعار أمينة والفريق يعرف ما يفعله.»',
      r1_name: 'عدنان عادي',
      r1_meta: 'منذ 6 أشهر',
      r2_text: '«تم تركيب حامل الشاحنة الخلفي في نفس اليوم. أسعار معقولة وبدون تعقيد. مخزون جيد من قطع الطرق الوعرة لن تجدها في مكان آخر بالشارقة.»',
      r2_name: 'هشام إرشاد',
      r2_meta: 'منذ شهرين',
      r3_text: '«فريق محترف. عمل متقن. كل تفصيلة في شاحنتي نُفِّذت بعناية — لا تسرع، لا اختصارات. أنصح بهم بشدة.»',
      r3_name: 'محمد ر.',
      r3_meta: 'منذ 4 أشهر',
      cs_whatsapp_label: 'واتساب — الأسرع رداً',
      cs_whatsapp_val: 'راسلنا الآن',
      cs_call_label: 'اتصل مباشرة',
      cs_call_val: '050 300 2898',
      cs_visit_label: 'تفضّل بزيارتنا — بدون موعد',
      cs_visit_val: 'المنطقة الصناعية 4، الشارقة',
      footer_tag: 'حديد الصحراء — للقوة والمتانة',
      footer_copy: '© 2025 جهروم لإكسسوارات السيارات، الشارقة',
      contact_hero_tag: 'تواصل معنا',
      contact_hero_h1_l1: 'تعال.',
      contact_hero_h1_l2: 'نبني.',
      contact_hero_sub: 'لا حاجة لموعد مسبق. تعال وأخبرنا عن شاحنتك وسنريك ما يمكن فعله.',
      contact_btn_wa: 'راسلنا على واتساب',
      contact_btn_call: 'اتصل: 050 300 2898',
      contact_email: 'h_jahrom@yahoo.com',
      contact_social_title: 'شاهد أعمالنا. تابعنا.',
      contact_instagram: 'إنستغرام',
      contact_youtube: 'يوتيوب',
      contact_tiktok: 'تيك توك',
      story_page_hero_sub: 'حرفة راسخة. صحراء الإمارات. أكثر من 22 عاماً في تجهيز أفضل شاحنات بيك آب في الشارقة.',
      story_ch1_title: 'البداية',
      story_ch1_h2_l1: 'صُنع في',
      story_ch1_h2_l2: 'الشارقة.',
      story_ch1_h2_l3: 'جذوره في',
      story_ch1_h2_l4: 'الحديد.',
      story_ch1_b1: 'تأسس جهروم منذ أكثر من عقدين في قلب الشارقة، انطلاقاً من قناعة راسخة: أن كل شاحنة تستحق اهتماماً احترافياً ودقة في التجهيز. ما بدأ كورشة متخصصة أصبح اليوم الوجهة الأولى لأصحاب البيك آب في الإمارات.',
      story_ch1_b2: 'حين أسّس هادي المتجر في المنطقة الصناعية 4 بالشارقة، جلب معه شغفاً بالتفاصيل. كان يعرف جيداً ما يريده أصحاب الشاحنات الجادون — ليس مجرد قطع، بل إكسسوارات ترتقي بسياراتهم فعلاً. منتجات مختارة بعناية، مُركَّبة بدقة، مدعومة بخبرة حقيقية.',
      story_ch1_b3: 'بعد أكثر من 22 عاماً، أصبح جهروم الخيار الأول لأصحاب البيك آب في الإمارات الذين لا يقبلون التنازل.',
      story_ch2_title: 'البيئة',
      story_ch2_h2_l1: 'مُصمَّم لـ',
      story_ch2_h2_l2: 'تضاريس',
      story_ch2_h2_l3: 'الإمارات.',
      story_ch2_b1: 'صيف يبلغ 48 درجة. رمال في كل مكان. أشعة فوق بنفسجية تدمر الطلاءات الرخيصة في أشهر. الإمارات من أقسى بيئات العالم على إكسسوارات الشاحنات — ومعظم المتاجر تتجاهل ذلك.',
      story_ch2_b2: 'نحن لا نتجاهله. كل منتج في جهروم اختُبر في هذا المناخ — ليس في مختبر، بل في حرارة الشارقة الحقيقية. أغطية صندوق تصدّ الغبار. حماية طلاء لا تصفر. عزل حراري يعمل فعلاً.',
      story_ch2_b3: 'إذا لم يتحمّل سنة كاملة في الإمارات، فلن تجده في صالة العرض لدينا. نقطة.',
      story_ch3_title: 'المنتجات',
      story_ch3_h2_l1: 'ما',
      story_ch3_h2_l2: 'نقدّمه',
      story_ch3_h2_l3: 'فعلاً.',
      story_ch3_b1: 'رام TRX. F-150 رابتور. GMC سييرا دينالي. جهّزناها جميعاً. جهروم متخصص في شاحنات البيك آب الأمريكية — الشاحنات التي يختارها أهل الإمارات حين يرفضون التنازل.',
      story_ch3_b2: 'أغطية صندوق — من الطيّ الثلاثي إلى الأغطية الصلبة القابلة للسحب. تعديلات خارجية — حواجز أمامية، درجات جانبية، رفوف سقف. حماية — طلاء PPF ذاتي الإصلاح. تفصيل داخلي — مقاعد وأرضيات جلدية بأي لون تختار.',
      story_ch3_b3: 'ولأننا نستورد مباشرة من المصنّعين، تبقى أسعارنا تنافسية دون المساس بالجودة. هذا هو الوعد الذي قطعه هادي حين فتح الأبواب — ووعد جهروم يُحفَظ كل يوم.',
      story_ch3_cta: 'تصفّح المنتجات',
      val1_title: 'تركيب دقيق',
      val1_body: 'كل إكسسوار مختار خصيصاً لشاحنات البيك آب الأمريكية. نعرف كل موديل وكل مواصفة. تركيب مثالي في كل مرة.',
      val2_title: 'أسعار عادلة',
      val2_body: 'تعاملنا المباشر مع الموردين يُلغي الوسيط. جودة عالية بأسعار تجعل الاختيار سهلاً.',
      val3_title: 'تركيب احترافي',
      val3_body: 'نحن لا نبيع فقط — بل نُركِّب. كل منتج تُثبِّته أيدي فريقنا الفني بمعايير المصنع.',
      val4_title: 'مُختبَر إماراتياً',
      val4_body: 'أكثر من 22 عاماً من الصحراء والحرارة والرمال اختبرت كل منتج نعرضه. إن وجدته عندنا، فقد أثبت جدارته.',
      val5_title: 'خبرة حقيقية',
      val5_body: 'لا تعرف ماذا تحتاج؟ تعال وتحدّث معنا — سنوصي بما يناسب شاحنتك وأسلوب قيادتك وميزانيتك.',
      val6_title: 'سمعة بالكلمة',
      val6_body: 'سمعتنا بُنيت بالكامل من زبائن عادوا مرة أخرى، وزبائن أحضروا أصدقاءهم.'
,
      prod_hero_h1: 'إكسسوارات وتعديلات الشاحنات',
      prod_hero_sub: 'الشارقة — المنطقة الصناعية 4',
      prod_tag: 'تصفّح المنتجات',
      filter_all: 'الكل',
      filter_beds: 'أغطية الصندوق',
      filter_exterior: 'خارجي',
      filter_interior: 'داخلي',
      filter_protection: 'حماية',
      filter_custom: 'مخصص',
      prod_1_name: 'غطاء صلب قابل للسحب',
      prod_1_spec: 'ألومنيوم 6063-T5 بجودة طيران. طلاء أسود غير لامع. مختبر بحمولة 500 رطل. مانع تسرب يحمي من غبار الإمارات. متوافق مع F-150 وRam وSierra.',
      prod_2_name: 'غطاء ثلاثي الطي الناعم',
      prod_2_spec: 'فينيل مقاوم للأشعة فوق البنفسجية. تثبيت بالمشبك دون حفر. يُفتح في ثوانٍ. متوافق مع F-Series وRam وTundra.',
      prod_3_name: 'حواجز أمامية',
      prod_3_spec: 'فولاذ وستانلس ستيل. طلاء أسود أو لامع. نقاط تثبيت LED. تركيب مباشر على F-150 وRam وSierra وSilverado.',
      prod_4_name: 'درجات جانبية',
      prod_4_spec: 'ألومنيوم وفولاذ. خيارات كهربائية قابلة للسحب. خطوات منخفضة للشاحنات المرفوعة. سطح مضاد للانزلاق، تركيب مباشر.',
      prod_5_name: 'رفوف السقف',
      prod_5_spec: 'أنظمة مثبّتة على الكابينة أو كاملة. فولاذ بطلاء مقاوم بتحمّل 150 كجم. قنوات LED مدمجة. أقواس خاصة بكل موديل.',
      prod_6_name: 'أقواس درع خلفي',
      prod_6_spec: 'أقواس فولاذية تُحدّد هوية الجزء الخلفي من شاحنتك. طلاء أسود مع أشرطة LED مدمجة وإضاءة عنبرية مميزة. تركيب مباشر على F-150 وRam وSierra وTundra.',
      prod_7_name: 'أرضيات جلدية وسجاد',
      prod_7_spec: 'تركيب جلد كامل بجميع الألوان. سجاد متين لكل الأحوال الجوية. غطاء خلفي ومقدمي. مقاوم لغبار الإمارات.',
      prod_8_name: 'حماية الطلاء PPF',
      prod_8_spec: 'فيلم حماية ذاتي الإصلاح. خيارات للمقدمة أو الكاملة. شفاف أو مات. يحمي من الشطف والخدوش والأشعة فوق البنفسجية.',
      prod_9_name: 'غطاء صلب كامل',
      prod_9_spec: 'غطاء صلب يحوّل صندوق شاحنتك إلى مساحة تخزين مغلقة ومقاومة للطقس. ألياف زجاجية مطابقة للون. نوافذ جانبية وإضاءة LED وقفل خلفي.',
      prod_10_name: 'حماية مخفية',
      prod_10_spec: 'حماية طلاء خفية للمناطق عالية التأثير — حواف الأبواب والأطراف والأقواس. غير مرئية. تحافظ على قيمة إعادة البيع.',
      prod_11_name: 'تجهيز مخصص كامل',
      prod_11_spec: 'لديك فكرة؟ نوفّر المواد ونضع المواصفات ونركّب وفق متطلباتك الدقيقة. من إكسسوار واحد إلى تحويل كامل.',
      pcard_cta: 'اطلب السعر ←',
      pcard_cta_custom: 'تحدّث معنا ←',
      dont_see_h: 'لا تجد',
      dont_see_h2: 'ما تبحث عنه؟',
      contact_hours_title: 'ساعات العمل والزيارة',
      contact_reach: 'تواصل',
      contact_out: 'معنا.',
      contact_wa_desc: 'واتساب هو الأسرع. أرسل لنا موديل شاحنتك وما تحتاجه — سنردّ عليك بالخيارات والأسعار خلال ساعة. بدون نماذج، بدون انتظار.',
      contact_find_us: 'جدنا.',
      contact_address: 'شارع صناعي أول 330، المنطقة الصناعية 4، الشارقة',
      cs_whatsapp_label: 'واتساب — الأسرع رداً',
      cs_call_label: 'اتصل مباشرة',
      cs_visit_label: 'تفضّل بزيارتنا — بدون موعد',
      cs_visit_val: 'المنطقة الصناعية 4، الشارقة'
    }
  },
  ur: {
    dir: 'rtl', font: 'Noto Nastaliq Urdu', label: 'اردو',
    t: {
      dir: 'rtl',
      font: 'Noto Nastaliq Urdu',
      label: 'اردو',
      nav_home: 'ہوم',
      nav_products: 'مصنوعات',
      nav_story: 'ہماری کہانی',
      nav_contact: 'رابطہ',
      nav_whatsapp: 'واٹس ایپ',
      pl_step1: 'لوڈ ہو رہا ہے...',
      pl_step2: 'تیاری جاری ہے...',
      pl_step3: 'تیار.',
      pl_sub: 'ریگستانی لوہا — 2004 سے — شارجہ، متحدہ عرب امارات',
      hero_tag: 'شارجہ، متحدہ عرب امارات — صنعتی علاقہ 4 — 2004 میں قائم',
      hero_l0: 'ریگستانی',
      hero_l1: 'لوہا.',
      hero_l2: 'تیار.',
      hero_sub: 'ان ڈرائیوروں کے لیے جو سمجھوتہ نہیں کرتے۔ 22 سال سے زائد تجربہ۔ 500 سے زیادہ گاڑیاں۔ ہر تنصیب شارجہ کے صنعتی علاقہ 4 میں ہاتھ سے کی جاتی ہے۔',
      hero_btn_products: 'مصنوعات دیکھیں',
      hero_btn_story: 'ہماری کہانی',
      stat_years: 'سال کا تجربہ',
      stat_rating: 'گوگل ریٹنگ',
      stat_trucks: 'گاڑیاں تیار',
      scroll_lbl: 'اسکرول کریں',
      tick1: 'بیڈ کور',
      tick2: 'خارجی تبدیلیاں',
      tick3: 'آڈیو سسٹم',
      tick4: 'پینٹ پروٹیکشن',
      tick5: 'اپہولسٹری',
      tick6: '4.7★ گوگل ریٹنگ',
      tick7: 'شارجہ، متحدہ عرب امارات',
      ts_tag: 'مصنوعات کا مظاہرہ',
      ts_sub: 'اسکرول کریں',
      ts_loading: 'لوڈ ہو رہا ہے',
      ts_p0_title: 'بنیادی تیاری',
      ts_p0_desc: 'ہر گاڑی بنیاد سے شروع ہوتی ہے — ہم جائزہ لیتے ہیں، منصوبہ بناتے ہیں، اور ہر اضافہ احتیاط سے چنتے ہیں۔ کوئی چیز بلا مقصد نہیں لگاتے۔',
      ts_p0_hint: '↓ اسکرول جاری رکھیں',
      ts_p1_title: 'مکمل سفاری سیٹ اپ',
      ts_p1_desc: 'روشنیاں، اضافے، مکمل کارکردگی۔ یہ ہے جہروم کا مکمل علاج — ہر بیرونی تبدیلی درستی سے، ہر روشنی سیٹ۔ متحدہ عرب امارات کے ریگستان اور اس سے آگے کے لیے۔',
      ts_p1_note: 'خارجی تعمیرات 8,000 درہم سے شروع',
      ts_p2_title: 'بجلی کی سائیڈ اسٹیپ',
      ts_p2_desc: 'بجلی کی سیڑھیاں جو دروازہ کھولتے ہی نکل آتی ہیں۔ گاڑی کی دہلیز پر درستی سے نصب، بند ہونے پر چھپی، استعمال میں مضبوط۔',
      ts_p2_note: 'سائیڈ اسٹیپ 2,200 درہم سے شروع',
      ts_p3_title: 'ٹرائی فولڈ بیڈ کور',
      ts_p3_desc: 'سخت تین حصوں والے کور جو بیڈ کو محفوظ رکھتے ہیں۔ واٹر پروف، کم اونچائی، مضبوط۔ سیکنڈوں میں کھلتے ہیں اور مضبوطی سے بند ہوتے ہیں۔',
      ts_p3_note: 'بیڈ کور 3,400 درہم سے شروع',
      ts_p4_title: 'کسٹم فرنٹ گرل',
      ts_p4_desc: 'کسٹم گرلیں جو گاڑی کا چہرہ بدل دیتی ہیں۔ ہر ایک اصل معیار پر نصب — بغیر سوراخ، بغیر خلا، بغیر ہلنے کے۔',
      ts_p4_note: 'گرلیں 1,800 درہم سے شروع',
      ts_p5_title: 'مکمل کیٹلاگ دیکھیں',
      ts_p5_desc: 'روف ریک، سنارکل، ونچ، لائٹنگ، PPF، آڈیو — جہروم کی مکمل رینج۔ ہر اضافہ اصلی، ہر تنصیب کی ضمانت۔',
      ts_p5_btn: 'مکمل کیٹلاگ دیکھیں',
      ts_hint_text: 'اسکرول کریں',
      ts_hint_sub: '3D تعاملی مظاہرے کے لیے اسکرول جاری رکھیں',
      booking_h3_l1: 'آپ کی گاڑی.',
      booking_h3_l2: 'آپ کی شرائط.',
      booking_text: 'انتظار کی فہرست نہیں۔ اضافی فروخت نہیں۔ اپنی گاڑی کا ماڈل بتائیں اور ہم بتائیں گے کیا مناسب ہے، کتنا خرچ ہوگا، اور کب تیار ہوگی۔',
      booking_btn_wa: 'واٹس ایپ',
      booking_btn_call: 'کال: 050 300 2898',
      booking_info: 'ہفتہ–جمعرات: صبح 8 تا رات 11، جمعہ: دوپہر 3 تا رات 11',
      story_section_tag: 'ہمارا سفر',
      story_section_h2_l1: 'خواب سے',
      story_section_h2_l2: 'حقیقت تک',
      stage1_tag: 'آغاز — 01 / 04',
      stage1_title: 'بنیاد',
      stage1_text: 'صنعتی علاقہ 4۔ 2004۔ ایک اصول: سنجیدہ گاڑیاں سنجیدہ اضافے مانگتی ہیں۔ باقی سب قابلِ گفتگو ہے۔',
      stage2_tag: 'طریقہ — 02 / 04',
      stage2_title: 'ہنر',
      stage2_text: 'کوئی ٹیمپلیٹ نہیں۔ کوئی جلد بازی نہیں۔ ہر تنصیب دو بار جانچی جاتی ہے۔ آپ کی گاڑی ہماری آخری نہیں — لیکن واحد ہے جو اس وقت اہم ہے۔',
      stage3_tag: 'ثبوت — 03 / 04',
      stage3_title: 'اعتماد',
      stage3_text: '4.7★ مارکیٹنگ سے نہیں آئی۔ 500 سے زیادہ گاڑیوں سے آئی جو امارات کی گرمی میں ابھی بھی فیکٹری جیسی دکھتی ہیں۔ بات پھیلتی ہے۔',
      stage4_tag: 'حال — 04 / 04',
      stage4_title: 'آج',
      stage4_text: 'رام TRX۔ F-150 ریپٹر۔ GMC سیرا ڈینالی۔ سب بنائی ہیں۔ آپ کی گاڑی کا اگلا سفر صنعتی علاقہ 4 سے شروع ہوتا ہے۔',
      reviews_h2_l1: 'گاہک',
      reviews_h2_l2: 'کیا کہتے ہیں.',
      rating_label: 'گوگل ریویوز',
      r1_text: '«شارجہ میں 4x4 اضافوں کے لیے بہترین دکان۔ انہیں اپنی گاڑیاں معلوم ہیں — ٹنڈرا، GMC، رام، F-150۔ قیمتیں منصفانہ اور ٹیم واقعی جانتی ہے۔»',
      r1_name: 'عدنان عادی',
      r1_meta: '6 ماہ پہلے',
      r2_text: '«ریئر ہچ کیریئر اسی دن لگ گئی۔ مناسب قیمتیں، سیدھا کام۔ آف روڈ پارٹس کا اچھا ذخیرہ جو شارجہ میں کہیں نہیں ملے گا۔»',
      r2_name: 'ہشام ارشاد',
      r2_meta: '2 ماہ پہلے',
      r3_text: '«پیشہ ور ٹیم۔ معیاری کام۔ میری گاڑی کی ہر تفصیل اچھی طرح سنبھالی گئی — جلد بازی نہیں، کمی نہیں۔ بہت سفارش کرتا ہوں۔»',
      r3_name: 'محمد ر.',
      r3_meta: '4 ماہ پہلے',
      cs_whatsapp_label: 'واٹس ایپ — تیز ترین جواب',
      cs_whatsapp_val: 'ابھی پیغام بھیجیں',
      cs_call_label: 'براہ راست کال',
      cs_call_val: '050 300 2898',
      cs_visit_label: 'آئیں — بغیر اپوائنٹمنٹ',
      cs_visit_val: 'صنعتی علاقہ 4، شارجہ',
      footer_tag: 'ریگستانی لوہا — طاقت کے لیے تیار',
      footer_copy: '© 2025 جہروم آٹو اکسیسریز، شارجہ',
      contact_hero_tag: 'رابطہ کریں',
      contact_hero_h1_l1: 'آئیں.',
      contact_hero_h1_l2: 'بنائیں.',
      contact_hero_sub: 'اپوائنٹمنٹ کی ضرورت نہیں۔ آئیں، اپنی گاڑی بتائیں، اور دیکھیں ہم کیا کر سکتے ہیں۔',
      contact_btn_wa: 'واٹس ایپ پر میسج',
      contact_btn_call: 'کال: 050 300 2898',
      contact_email: 'h_jahrom@yahoo.com',
      contact_social_title: 'کام دیکھیں۔ فالو کریں۔',
      contact_instagram: 'انسٹاگرام',
      contact_youtube: 'یوٹیوب',
      contact_tiktok: 'ٹک ٹاک',
      story_page_hero_sub: 'پختہ ہنر۔ امارات کا ریگستان۔ 22 سال سے زیادہ شارجہ میں بہترین پک اپ ٹرک تیار کرنے کا تجربہ۔',
      story_ch1_title: 'آغاز',
      story_ch1_h2_l1: 'شارجہ میں',
      story_ch1_h2_l2: 'تعمیر.',
      story_ch1_h2_l3: 'لوہے میں',
      story_ch1_h2_l4: 'جڑیں.',
      story_ch1_b1: 'دو دہائیوں سے زائد قبل شارجہ کے قلب میں قائم، جہروم ایک یقین پر کھڑا ہوا: ہر گاڑی پیشہ ورانہ توجہ اور درست تنصیب کی مستحق ہے۔ جو ایک خصوصی ورکشاپ سے شروع ہوا وہ آج متحدہ عرب امارات میں پک اپ ٹرک اضافوں کی سب سے قابل اعتماد منزل بن گئی ہے۔',
      story_ch1_b2: 'جب ہادی نے شارجہ کے صنعتی علاقہ 4 میں دکان کھولی، تو وہ تفصیل سے محبت ساتھ لائے۔ وہ جانتے تھے سنجیدہ ٹرک مالکان کو کیا چاہیے — محض پرزے نہیں، بلکہ اضافے جو واقعی گاڑی کو بہتر بنائیں۔ سوچ کر چنے گئے، درستی سے لگائے گئے، حقیقی علم سے پشت پناہ کیے گئے۔',
      story_ch1_b3: '22 سال سے زائد گزرنے کے بعد، جہروم پورے متحدہ عرب امارات میں پک اپ ٹرک مالکان کی پہلی پسند بن گئی ہے جو سمجھوتہ سے انکاری ہیں۔',
      story_ch2_title: 'ماحول',
      story_ch2_h2_l1: 'امارات کی',
      story_ch2_h2_l2: 'زمین',
      story_ch2_h2_l3: 'کے لیے.',
      story_ch2_b1: '48 ڈگری گرمی۔ ہر جگہ ریت۔ الٹراوائلٹ شعاعیں جو سستے رنگ مہینوں میں برباد کر دیتی ہیں۔ متحدہ عرب امارات ٹرک اضافوں کے لیے دنیا کے سب سے سخت ماحول میں سے ہے — اور زیادہ تر دکانیں یہ نظر انداز کرتی ہیں۔',
      story_ch2_b2: 'ہم نہیں کرتے۔ جہروم کی ہر مصنوعات اسی آب و ہوا میں آزمائی گئی ہے — لیب میں نہیں، شارجہ کی اصل گرمی میں۔ بیڈ کور جو صحرائی دھول روکتے ہیں۔ PPF جو پیلا نہیں ہوتا۔ حرارت کا تحفظ جو کام کرتا ہے۔',
      story_ch2_b3: 'اگر یہ متحدہ عرب امارات کا پورا سال نہیں جھیل سکتی، تو ہمارے شوروم میں جگہ نہیں ملے گی۔ بس۔',
      story_ch3_title: 'مصنوعات',
      story_ch3_h2_l1: 'ہم',
      story_ch3_h2_l2: 'اصل میں',
      story_ch3_h2_l3: 'کیا کرتے ہیں.',
      story_ch3_b1: 'رام TRX۔ F-150 ریپٹر۔ GMC سیرا ڈینالی۔ سب بنائی ہیں۔ جہروم امریکی پک اپ ٹرکوں میں مہارت رکھتا ہے — وہ گاڑیاں جو امارات کے ڈرائیور سمجھوتہ نہ کرنے پر چنتے ہیں۔',
      story_ch3_b2: 'بیڈ کور — سخت قابلِ سحب ڈھکنوں سے لے کر نرم تین حصوں والے کور تک۔ خارجی تعمیرات — بل باز، ریننگ بورڈز، روف ریک۔ تحفظ — خود کو ٹھیک کرنے والا PPF۔ داخلی تفصیل — کسی بھی رنگ میں مکمل چمڑے کی نشستیں اور فرش۔',
      story_ch3_b3: 'اور کیونکہ ہم براہ راست مینوفیکچررز سے خریدتے ہیں، ہماری قیمتیں معیار سے سمجھوتہ کیے بغیر مسابقتی رہتی ہیں۔ یہی وعدہ ہادی نے دروازے کھولتے وقت کیا تھا — اور جہروم یہ وعدہ ہر روز نبھاتا ہے۔',
      story_ch3_cta: 'مصنوعات دیکھیں',
      val1_title: 'درست تنصیب',
      val1_body: 'ہر اضافہ امریکی پک اپ ٹرکوں کے لیے خاص طور پر چنا جاتا ہے۔ ہر ماڈل، ہر سپیسیفیکیشن جانتے ہیں۔ ہر بار بے عیب فٹنگ۔',
      val2_title: 'منصفانہ قیمتیں',
      val2_body: 'سپلائر سے براہ راست تعلق درمیانی آدمی کو ختم کرتا ہے۔ اعلی معیار، مناسب قیمت۔',
      val3_title: 'پیشہ ورانہ تنصیب',
      val3_body: 'ہم صرف بیچتے نہیں — لگاتے بھی ہیں۔ ہر مصنوع ہماری تکنیکی ٹیم کے ہاتھوں فیکٹری معیار پر نصب۔',
      val4_title: 'امارات میں آزمودہ',
      val4_body: '22 سال سے زیادہ کے صحرا، گرمی اور ریت نے ہر مصنوع کو پرکھا ہے۔ اگر ہمارے پاس ہے تو ثابت ہو چکی ہے۔',
      val5_title: 'ماہرانہ رہنمائی',
      val5_body: 'نہیں جانتے کیا چاہیے؟ آئیں اور بات کریں — ہم بتائیں گے آپ کی گاڑی، ڈرائیونگ اور بجٹ کے مطابق کیا بہترین ہے۔',
      val6_title: 'زبانی شہرت',
      val6_body: 'ہماری شہرت مکمل طور پر ان گاہکوں سے بنی ہے جو واپس آئے، اور انہوں نے جو دوستوں کو بھیجا۔'
,
      prod_hero_h1: 'ٹرک اکسیسریز اور بلڈز',
      prod_hero_sub: 'شارجہ، متحدہ عرب امارات — صنعتی علاقہ 4',
      prod_tag: 'مصنوعات دیکھیں',
      filter_all: 'سب',
      filter_beds: 'بیڈ کور',
      filter_exterior: 'بیرونی',
      filter_interior: 'اندرونی',
      filter_protection: 'تحفظ',
      filter_custom: 'کسٹم',
      prod_1_name: 'ہارڈ ٹاپ ریٹریکٹیبل',
      prod_1_spec: 'ایرو اسپیس گریڈ 6063-T5 ایلومینیم۔ میٹ بلیک کوٹنگ۔ 500 پاؤنڈ لوڈ ٹیسٹ۔ دھول سے محفوظ سیل۔ F-150، Ram، Sierra کے لیے موزوں۔',
      prod_2_name: 'سافٹ ٹرائی-فولڈ',
      prod_2_spec: 'UV مزاحم ونائل۔ کلیمپ فٹنگ — بغیر سوراخ۔ سیکنڈوں میں کھلتا ہے۔ F-Series، Ram، Tundra کے لیے موزوں۔',
      prod_3_name: 'بل بار',
      prod_3_spec: 'مائلڈ اسٹیل اور سٹینلس۔ بلیک یا پالش کوٹنگ۔ LED ماؤنٹ پوائنٹس۔ F-150، Ram، Sierra کے لیے براہ راست۔',
      prod_4_name: 'رننگ بورڈز',
      prod_4_spec: 'ایلومینیم اور اسٹیل۔ بجلی کے قابل سحب آپشن۔ اونچے ٹرکوں کے لیے ڈراپ اسٹیپ۔ نان-سلپ سطح۔',
      prod_5_name: 'روف ریک',
      prod_5_spec: 'کیبن یا فل-لینتھ سسٹم۔ 150 کلو گرام تک کوٹڈ اسٹیل۔ LED چینلز۔ ہر ماڈل کے لیے خاص بریکٹس۔',
      prod_6_name: 'رول بار',
      prod_6_spec: 'بھاری اسٹیل رول بار جو ٹرک کی پشت کو تعریف دیتے ہیں۔ بلیک کوٹنگ، LED لائٹ بار اور امبر سٹرپ لائٹنگ۔ F-150، Ram، Sierra، Tundra کے لیے براہ راست۔',
      prod_7_name: 'فلور لیدر اور میٹس',
      prod_7_spec: 'تمام رنگوں میں مکمل چمڑے کی تنصیب۔ ہر موسم کے لیے میٹس۔ اینٹی-سلپ۔ آگے، پیچھے اور کارگو ایریا۔',
      prod_8_name: 'PPF اور پینٹ پروٹیکشن',
      prod_8_spec: 'خود مرمت پینٹ پروٹیکشن فلم۔ مکمل یا جزوی آپشن۔ UV سے تحفظ اور خروں سے بچاؤ۔',
      prod_9_name: 'ہارڈ ٹاپ کینوپی',
      prod_9_spec: 'مکمل ہارڈ شیل کینوپی جو بیڈ کو محفوظ کارگو اسپیس میں بدل دیتی ہے۔ رنگ سے میل کھاتی فائبرگلاس۔ سائیڈ ونڈوز، LED لائٹنگ، لاک۔',
      prod_10_name: 'مخفی تحفظ',
      prod_10_spec: 'زیادہ اثر والے حصوں کے لیے پوشیدہ پینٹ پروٹیکشن — دروازے، آرچز۔ نظر نہیں آتی۔ بیچنے کی قیمت بچاتی ہے۔',
      prod_11_name: 'مکمل کسٹم بلڈ',
      prod_11_spec: 'آپ کا خیال ہے؟ ہم سورس، سپیک اور نصب کرتے ہیں بالکل آپ کی ضرورت کے مطابق۔',
      pcard_cta: 'قیمت معلوم کریں ←',
      pcard_cta_custom: 'بات کریں ←',
      dont_see_h: 'نہیں ملا',
      dont_see_h2: 'جو آپ چاہتے ہیں؟',
      contact_hours_title: 'اوقات اور وزٹ',
      contact_reach: 'رابطہ',
      contact_out: 'کریں.',
      contact_wa_desc: 'واٹس ایپ سب سے تیز ہے۔ اپنی گاڑی کا ماڈل بھیجیں — ہم ایک گھنٹے میں قیمت اور آپشن دیں گے۔',
      contact_find_us: 'ہمیں ڈھونڈیں.',
      contact_address: '330 فرسٹ انڈسٹریل سٹریٹ، صنعتی علاقہ 4، شارجہ',
      cs_whatsapp_label: 'واٹس ایپ — تیز ترین جواب',
      cs_call_label: 'براہ راست کال',
      cs_visit_label: 'آئیں — بغیر اپوائنٹمنٹ',
      cs_visit_val: 'صنعتی علاقہ 4، شارجہ'
    }
  }};

// ─── Font loader ───────────────────────────────────────────────────────────────
function juhrumLoadFont(fontName) {
  if (!fontName) return;
  const id = 'juhrum-lang-font';
  let el = document.getElementById(id);
  if (!el) { el = document.createElement('style'); el.id = id; document.head.appendChild(el); }
  const map = {
    'Noto Sans Arabic': 'https://fonts.googleapis.com/css2?family=Noto+Sans+Arabic:wght@300;400;600&display=swap',
    'Noto Nastaliq Urdu': 'https://fonts.googleapis.com/css2?family=Noto+Nastaliq+Urdu:wght@400;700&display=swap',
    'Noto Sans Devanagari': 'https://fonts.googleapis.com/css2?family=Noto+Sans+Devanagari:wght@300;400;600&display=swap',
  };
  const url = map[fontName];
  if (!url) return;
  el.textContent = `@import url('${url}'); [data-lang-active] { font-family: '${fontName}', sans-serif !important; }`;
}

// ─── Core apply function ────────────────────────────────────────────────────────
function juhrumApplyLang(code) {
  const lang = JUHRUM_LANGS[code];
  if (!lang) return;

  localStorage.setItem('juhrum-lang', code);
  document.documentElement.setAttribute('lang', code);
  document.documentElement.setAttribute('dir', lang.dir);
  document.documentElement.setAttribute('data-lang-active', code);

  // RTL body class for layout adjustments
  document.body.classList.toggle('rtl', lang.dir === 'rtl');

  // Load font
  juhrumLoadFont(lang.font);

  // Apply translations
  const t = lang.t;
  document.querySelectorAll('[data-i18n]').forEach(function(el) {
    const key = el.getAttribute('data-i18n');
    if (t[key] !== undefined) {
      // Preserve inner HTML tags (e.g. <strong>, <em>, <br>)
      if (el.innerHTML.includes('<') && !el.innerHTML.includes('data-i18n')) {
        el.innerHTML = t[key];
      } else {
        el.textContent = t[key];
      }
    }
  });

  // Handle placeholder translations (inputs)
  document.querySelectorAll('[data-i18n-placeholder]').forEach(function(el) {
    const key = el.getAttribute('data-i18n-placeholder');
    if (t[key] !== undefined) el.setAttribute('placeholder', t[key]);
  });

  // Sync dropdown UI if present
  var menu = document.getElementById('langDropMenu');
  var label = document.getElementById('langDropLabel');
  if (menu && label) {
    menu.querySelectorAll('.lang-drop-item').forEach(function(item) {
      const isActive = item.getAttribute('data-lang') === code;
      item.classList.toggle('active', isActive);
      if (isActive) label.textContent = lang.label;
    });
  }
}

// ─── Init ───────────────────────────────────────────────────────────────────────
function juhrumInitLang() {
  const saved = localStorage.getItem('juhrum-lang') || 'en';
  juhrumApplyLang(saved);
}

window.juhrumApplyLang = juhrumApplyLang;
window.juhrumInitLang  = juhrumInitLang;
window.JUHRUM_LANGS    = JUHRUM_LANGS;

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', juhrumInitLang);
} else {
  juhrumInitLang();
}
