/**
 * Jahrom Language System — v3
 * EN / AR / UR / FA / HI
 * RTL: AR, UR, FA | LTR: EN, HI
 */

const JUHRUM_LANGS = {
  en: {
    dir: 'ltr', font: null, label: 'EN',
    t: {
      nav_home: 'Home',
      nav_products: 'Products',
      nav_story: 'Our Story',
      nav_contact: 'Contact',
      nav_whatsapp: 'WhatsApp Us',
      pl_step1: 'Calibrating...',
      pl_step2: 'Building...',
      pl_step3: 'Ready.',
      pl_sub: 'Desert Iron — Est. 2004 — Sharjah UAE',
      hero_tag: 'Sharjah, UAE — Industrial Area 4 — Est. 2004',
      hero_l0: 'DESERT',
      hero_l1: 'IRON.',
      hero_l2: 'BUILT.',
      hero_sub: 'Built for drivers who don\'t compromise. Over 22 years. 500+ builds. Every truck hand-fitted in Sharjah\'s Industrial Area 4.',
      hero_btn_products: 'View Products',
      hero_btn_story: 'Our Story',
      stat_years: 'Years Experience',
      stat_rating: 'Google Rating',
      stat_trucks: 'Trucks Built',
      scroll_lbl: 'Scroll to Explore',
      tick1: 'Bed Covers',
      tick2: 'Exterior Builds',
      tick3: 'Audio Systems',
      tick4: 'Paint Protection',
      tick5: 'Upholstery',
      tick6: '4.7★ Google Rating',
      tick7: 'Sharjah UAE',
      ts_tag: 'Product Showcase',
      ts_sub: 'Scroll to explore',
      ts_loading: 'Loading',
      ts_p0_title: 'The Base Build',
      ts_p0_desc: 'Every Jahrom build starts with the stock truck — a blank canvas. We assess the vehicle, plan the build, and source every accessory to spec. Nothing gets fitted that doesn\'t belong.',
      ts_p0_hint: '↓ Keep scrolling',
      ts_p1_title: 'Full Safari Build',
      ts_p1_desc: 'Lights on. Accessories locked in. This is the complete Jahrom treatment — every exterior mod fitted flush, every light dialled in. Built for the UAE desert and beyond.',
      ts_p1_note: 'Exterior builds from AED 8,000',
      ts_p2_title: 'Power Side Step',
      ts_p2_desc: 'Electric retractable side steps that deploy the moment you open the door. Precision-fitted to your truck\'s sill, flush when closed, solid underfoot when extended. No rattle. No gap.',
      ts_p2_note: 'Steps from AED 2,200 fitted',
      ts_p3_title: 'Tri-Fold Bed Cover',
      ts_p3_desc: 'Hard tri-fold tonneau covers that lock your bed down. Weatherproof, low-profile, and strong enough to stand on. Opens fully in seconds, locks tight for highway speeds.',
      ts_p3_note: 'Bed covers from AED 3,400 fitted',
      ts_p4_title: 'Front Grille',
      ts_p4_desc: 'Custom billet and mesh grilles that transform the face of the truck. Every grille is fitted with OEM precision — no drilling, no gaps, no flex. Your truck\'s most visible statement.',
      ts_p4_note: 'Grilles from AED 1,800 fitted',
      ts_p5_title: 'See the Full Catalogue',
      ts_p5_desc: 'Roof racks, snorkels, winches, lighting rigs, PPF, audio builds — the full Jahrom range. Every accessory sourced, every fitment guaranteed.',
      ts_p5_btn: 'View Full Catalogue',
      ts_hint_text: 'Scroll to Build',
      ts_hint_sub: 'Keep scrolling for 3D interactive showcase',
      booking_h3_l1: 'YOUR TRUCK.',
      booking_h3_l2: 'YOUR TERMS.',
      booking_text: 'No waiting lists. No upselling. Tell us your truck, we\'ll tell you exactly what fits, what it costs, and when it\'s done.',
      booking_btn_wa: 'WhatsApp Us',
      booking_btn_call: 'Call: 050 300 2898',
      booking_info: 'Open Sat–Thu: 8AM–11PM, Fri: 3PM–11PM',
      story_section_tag: 'Our Journey',
      story_section_h2_l1: 'FROM VISION TO',
      story_section_h2_l2: 'REALITY',
      stage1_tag: 'The Origin — 01 / 04',
      stage1_title: 'Foundation',
      stage1_text: 'Industrial Area 4. 2004. One rule: serious trucks deserve serious gear. Everything else is negotiable.',
      stage2_tag: 'The Method — 02 / 04',
      stage2_title: 'Craft',
      stage2_text: 'No templates. No rush jobs. Every fit verified twice. Your Silverado isn\'t our last Silverado — it\'s the only one that matters.',
      stage3_tag: 'The Proof — 03 / 04',
      stage3_title: 'Trusted',
      stage3_text: '4.7★ didn\'t come from marketing. It came from 500+ trucks that still look factory-fresh in UAE heat. Word travels.',
      stage4_tag: 'The Present — 04 / 04',
      stage4_title: 'Today',
      stage4_text: 'Ram TRX. F-150 Raptor. GMC Sierra Denali. Built them all. Your truck\'s next chapter starts in Industrial Area 4.',
      reviews_h2_l1: 'WHAT THEY',
      reviews_h2_l2: 'SAY.',
      rating_label: 'Google Reviews',
      r1_text: '"Best shop for 4x4 accessories in Sharjah. They know their trucks — Tundra, GMC, Ram, F-150. Prices are honest and the team actually knows what they\'re doing."',
      r1_name: 'Adnan Aadi',
      r1_meta: '6 months ago',
      r2_text: '"Got a rear hitch carrier fitted same day. Fair prices, no nonsense. Good stock of offroad parts that you won\'t find elsewhere in Sharjah."',
      r2_name: 'Hisham Irshad',
      r2_meta: '2 months ago',
      r3_text: '"Professional team. Quality work. Every detail on my truck was handled properly — not rushed, not cut short. Highly recommended."',
      r3_name: 'Mohammed R.',
      r3_meta: '4 months ago',
      cs_whatsapp_label: 'WhatsApp — Fastest Response',
      cs_whatsapp_val: 'Message Us Now',
      cs_call_label: 'Call Direct',
      cs_call_val: '050 300 2898',
      cs_visit_label: 'Walk In — No Appointment',
      cs_visit_val: 'Industrial Area 4, Sharjah',
      footer_tag: 'Desert Iron — Built for Power',
      footer_copy: '© 2025 Jahrom Auto Accessories, Sharjah UAE',
      contact_hero_tag: 'Get In Touch',
      contact_hero_h1_l1: 'COME IN.',
      contact_hero_h1_l2: 'BUILD IT.',
      contact_hero_sub: 'No appointment needed. Walk in, tell us about your truck, and we\'ll show you what\'s possible.',
      contact_btn_wa: 'Message on WhatsApp',
      contact_btn_call: 'Call: 050 300 2898',
      contact_email: 'h_jahrom@yahoo.com',
      contact_social_title: 'See the builds. Follow us.',
      contact_instagram: 'Instagram',
      contact_youtube: 'YouTube',
      contact_tiktok: 'TikTok',
      story_page_hero_sub: 'Expert craftsmanship. UAE desert. Over 22 years of building the best pickup trucks in Sharjah.',
      story_ch1_title: 'The Origin',
      story_ch1_h2_l1: 'BUILT IN',
      story_ch1_h2_l2: 'SHARJAH.',
      story_ch1_h2_l3: 'RAISED ON',
      story_ch1_h2_l4: 'IRON.',
      story_ch1_b1: 'Founded over two decades ago in the heart of Sharjah, Jahrom was built on a single belief: that every truck deserves expert-level attention and precision craftsmanship. What started as a specialist workshop became the UAE\'s most trusted pickup truck accessories destination.',
      story_ch1_b2: 'When Hadi established the shop in Sharjah\'s Industrial Area 4, he brought a deep passion for detail with him. He knew exactly what serious truck owners wanted — not just parts, but accessories that genuinely elevated their vehicle. Products chosen with care, fitted with precision, backed with knowledge.',
      story_ch1_b3: 'Over 22 years later, Jahrom has become the go-to destination for pickup truck owners across the UAE who refuse to compromise.',
      story_ch2_title: 'The Environment',
      story_ch2_h2_l1: 'BUILT FOR',
      story_ch2_h2_l2: 'UAE',
      story_ch2_h2_l3: 'TERRAIN.',
      story_ch2_b1: '48°C summers. Sand in every seal. UV that destroys cheap coatings within months. The UAE is one of the most punishing environments on earth for truck accessories — and most shops ignore that.',
      story_ch2_b2: 'We don\'t. Every product at Jahrom has been tested against this climate — not in a lab, but in the real heat of Sharjah summers. Bed covers that lock out desert dust. PPF that doesn\'t yellow. Thermal insulation that actually works.',
      story_ch2_b3: 'If it can\'t handle a full UAE year, it doesn\'t earn a place in our showroom. Full stop.',
      story_ch3_title: 'The Products',
      story_ch3_h2_l1: 'WHAT WE',
      story_ch3_h2_l2: 'ACTUALLY',
      story_ch3_h2_l3: 'DO.',
      story_ch3_b1: 'Ram TRX. F-150 Raptor. GMC Sierra Denali. We\'ve built them all. Jahrom specialises in American pickup trucks — the trucks UAE drivers actually choose when they refuse to compromise.',
      story_ch3_b2: 'Bed covers — from retractable hardtops to soft tri-fold covers. Exterior builds — bull bars, running boards, roof racks. Protection — self-healing PPF. Interior — full leather seat and floor installations in any colour.',
      story_ch3_b3: 'And because we source directly from manufacturers, our prices remain competitive without compromising on quality. That\'s the promise Hadi made when he opened the doors — and it\'s the promise Jahrom keeps every day.',
      story_ch3_cta: 'Browse Products',
      val1_title: 'Precision Fit',
      val1_body: 'Every accessory sourced specifically for American pickup trucks. We know every model, every spec, every year. Perfect fitment every time.',
      val2_title: 'Fair Pricing',
      val2_body: 'Direct supplier relationships mean we eliminate the middleman. Premium quality at prices that don\'t make you choose between good gear and a fair deal.',
      val3_title: 'Professional Installation',
      val3_body: 'We don\'t just sell — we fit. Every product installed by our technical team to factory-finish standard.',
      val4_title: 'UAE-Proven',
      val4_body: 'Over 22 years of UAE desert, heat, and sand have tested every product we stock. If it\'s in our showroom, it earned its place.',
      val5_title: 'Expert Guidance',
      val5_body: 'Not sure what you need? Come in and talk to us — we\'ll recommend exactly what fits your truck, your driving, and your budget.',
      val6_title: 'Word of Mouth',
      val6_body: 'Our reputation has been built entirely by customers who came back, and customers who sent their friends.'
    }
  },
  ar: {
    dir: 'rtl', font: 'Noto Sans Arabic', label: 'عربي',
    t: {
      dir: 'rtl',
      font: 'Noto Sans Arabic',
      label: 'عربي',
      nav_home: 'الرئيسية',
      nav_products: 'المنتجات',
      nav_story: 'قصتنا',
      nav_contact: 'تواصل معنا',
      nav_whatsapp: 'واتساب',
      pl_step1: 'جارٍ التحميل...',
      pl_step2: 'لحظة...',
      pl_step3: 'جاهز.',
      pl_sub: 'حديد الصحراء — منذ 2004 — الشارقة',
      hero_tag: 'الشارقة، الإمارات — المنطقة الصناعية 4 — تأسس 2004',
      hero_l0: 'حديد',
      hero_l1: 'الصحراء.',
      hero_l2: 'مُصنَّع.',
      hero_sub: 'للسائق الذي لا يقبل المساومة. أكثر من 22 عاماً. 500+ سيارة مُجهَّزة. كل شيء يتم بأيدي متخصصة في المنطقة الصناعية 4 بالشارقة.',
      hero_btn_products: 'تصفّح المنتجات',
      hero_btn_story: 'قصتنا',
      stat_years: 'سنة خبرة',
      stat_rating: 'تقييم جوجل',
      stat_trucks: 'تجهيز شاحنات',
      scroll_lbl: 'مرّر للاستكشاف',
      tick1: 'أغطية الصندوق',
      tick2: 'تعديلات خارجية',
      tick3: 'أنظمة صوتية',
      tick4: 'حماية الطلاء',
      tick5: 'تفصيل داخلي',
      tick6: '4.7★ تقييم جوجل',
      tick7: 'الشارقة، الإمارات',
      ts_tag: 'عرض المنتجات',
      ts_sub: 'مرّر للاستكشاف',
      ts_loading: 'جارٍ التحميل',
      ts_p0_title: 'البناء الأساسي',
      ts_p0_desc: 'كل سيارة تبدأ من الصفر — نُقيِّم، نخطط، ونختار كل قطعة بعناية. لا شيء يُركَّب دون سبب.',
      ts_p0_hint: '↓ استمر في التمرير',
      ts_p1_title: 'تجهيز سفاري كامل',
      ts_p1_desc: 'إضاءة، إكسسوارات، وأداء متكامل. هذا هو التجهيز الكامل من جهروم — كل قطعة خارجية مثبّتة بدقة، كل إضاءة مُعايَرة. مُصمَّم لصحراء الإمارات وما بعدها.',
      ts_p1_note: 'التجهيزات الخارجية تبدأ من 8,000 درهم',
      ts_p2_title: 'درجة جانبية كهربائية',
      ts_p2_desc: 'درجات جانبية كهربائية تنسحب فور فتح الباب. مثبّتة بدقة على عتبة سيارتك، مخفية عند الإغلاق، متينة عند الاستخدام. بلا اهتزاز ولا فجوات.',
      ts_p2_note: 'الدرجات الجانبية تبدأ من 2,200 درهم مع التركيب',
      ts_p3_title: 'غطاء صندوق ثلاثي الطي',
      ts_p3_desc: 'أغطية صلبة ثلاثية الطي تحمي صندوق شاحنتك. مقاومة للماء، منخفضة المستوى، وقوية. تُفتح بالكامل في ثوانٍ وتُغلَق بإحكام.',
      ts_p3_note: 'الأغطية تبدأ من 3,400 درهم مع التركيب',
      ts_p4_title: 'شبكة مقدمة مخصصة',
      ts_p4_desc: 'شبكات مقدمة مخصصة تُغيِّر ملامح شاحنتك. كل واحدة مُركَّبة بدقة — بدون حفر، بدون فجوات، بدون اهتزاز.',
      ts_p4_note: 'الشبكات تبدأ من 1,800 درهم مع التركيب',
      ts_p5_title: 'اكتشف الكتالوج الكامل',
      ts_p5_desc: 'رفوف السقف، الشنوركل، الونشات، أنظمة الإضاءة، حماية الطلاء، أنظمة صوتية — الكتالوج الكامل لجهروم. كل قطعة بأصالة، كل تركيب مضمون.',
      ts_p5_btn: 'عرض الكتالوج الكامل',
      ts_hint_text: 'مرّر للبناء',
      ts_hint_sub: 'استمر بالتمرير للعرض التفاعلي ثلاثي الأبعاد',
      booking_h3_l1: 'سيارتك.',
      booking_h3_l2: 'بشروطك.',
      booking_text: 'بلا قوائم انتظار. بلا مبالغة في البيع. أخبرنا بموديل سيارتك وسنخبرك بما يناسبها والسعر الدقيق ووقت الانتهاء.',
      booking_btn_wa: 'واتساب',
      booking_btn_call: 'اتصل: 050 300 2898',
      booking_info: 'السبت–الخميس: 8ص–11م، الجمعة: 3م–11م',
      story_section_tag: 'مسيرتنا',
      story_section_h2_l1: 'من الفكرة إلى',
      story_section_h2_l2: 'الواقع',
      stage1_tag: 'البداية — 01 / 04',
      stage1_title: 'التأسيس',
      stage1_text: 'المنطقة الصناعية 4. 2004. قاعدة واحدة: الشاحنات الجادة تستحق معدات جادة. وكل ما عدا ذلك قابل للتفاوض.',
      stage2_tag: 'الأسلوب — 02 / 04',
      stage2_title: 'الحرفة',
      stage2_text: 'لا قوالب جاهزة. لا أعمال متسرعة. كل تركيب يُتحقق منه مرتين. سيارتك ليست آخر سيارة نُجهِّزها — لكنها الوحيدة التي تهم.',
      stage3_tag: 'الإثبات — 03 / 04',
      stage3_title: 'الثقة',
      stage3_text: 'تقييم 4.7★ لم يأتِ من حملات تسويقية. جاء من أكثر من 500 شاحنة لا تزال تبدو كما خرجت من المصنع في حرارة الإمارات. الكلمة تنتشر.',
      stage4_tag: 'الحاضر — 04 / 04',
      stage4_title: 'اليوم',
      stage4_text: 'رام TRX. F-150 رابتور. GMC سييرا دينالي. بنيناها جميعاً. قصة شاحنتك القادمة تبدأ في المنطقة الصناعية 4.',
      reviews_h2_l1: 'ماذا يقول',
      reviews_h2_l2: 'عملاؤنا.',
      rating_label: 'تقييمات جوجل',
      r1_text: '«أفضل متجر لإكسسوارات الدفع الرباعي في الشارقة. يعرفون شاحناتهم — تندرا، GMC، رام، F-150. الأسعار أمينة والفريق يعرف ما يفعله.»',
      r1_name: 'عدنان عادي',
      r1_meta: 'منذ 6 أشهر',
      r2_text: '«تم تركيب حامل الشاحنة الخلفي في نفس اليوم. أسعار معقولة وبدون تعقيد. مخزون جيد من قطع الطرق الوعرة لن تجدها في مكان آخر بالشارقة.»',
      r2_name: 'هشام إرشاد',
      r2_meta: 'منذ شهرين',
      r3_text: '«فريق محترف. عمل متقن. كل تفصيلة في شاحنتي نُفِّذت بعناية — لا تسرع، لا اختصارات. أنصح بهم بشدة.»',
      r3_name: 'محمد ر.',
      r3_meta: 'منذ 4 أشهر',
      cs_whatsapp_label: 'واتساب — الأسرع رداً',
      cs_whatsapp_val: 'راسلنا الآن',
      cs_call_label: 'اتصل مباشرة',
      cs_call_val: '050 300 2898',
      cs_visit_label: 'تفضّل بزيارتنا — بدون موعد',
      cs_visit_val: 'المنطقة الصناعية 4، الشارقة',
      footer_tag: 'حديد الصحراء — للقوة والمتانة',
      footer_copy: '© 2025 جهروم لإكسسوارات السيارات، الشارقة',
      contact_hero_tag: 'تواصل معنا',
      contact_hero_h1_l1: 'تعال.',
      contact_hero_h1_l2: 'نبني.',
      contact_hero_sub: 'لا حاجة لموعد مسبق. تعال وأخبرنا عن شاحنتك وسنريك ما يمكن فعله.',
      contact_btn_wa: 'راسلنا على واتساب',
      contact_btn_call: 'اتصل: 050 300 2898',
      contact_email: 'h_jahrom@yahoo.com',
      contact_social_title: 'شاهد أعمالنا. تابعنا.',
      contact_instagram: 'إنستغرام',
      contact_youtube: 'يوتيوب',
      contact_tiktok: 'تيك توك',
      story_page_hero_sub: 'حرفة راسخة. صحراء الإمارات. أكثر من 22 عاماً في تجهيز أفضل شاحنات بيك آب في الشارقة.',
      story_ch1_title: 'البداية',
      story_ch1_h2_l1: 'صُنع في',
      story_ch1_h2_l2: 'الشارقة.',
      story_ch1_h2_l3: 'جذوره في',
      story_ch1_h2_l4: 'الحديد.',
      story_ch1_b1: 'تأسس جهروم منذ أكثر من عقدين في قلب الشارقة، انطلاقاً من قناعة راسخة: أن كل شاحنة تستحق اهتماماً احترافياً ودقة في التجهيز. ما بدأ كورشة متخصصة أصبح اليوم الوجهة الأولى لأصحاب البيك آب في الإمارات.',
      story_ch1_b2: 'حين أسّس هادي المتجر في المنطقة الصناعية 4 بالشارقة، جلب معه شغفاً بالتفاصيل. كان يعرف جيداً ما يريده أصحاب الشاحنات الجادون — ليس مجرد قطع، بل إكسسوارات ترتقي بسياراتهم فعلاً. منتجات مختارة بعناية، مُركَّبة بدقة، مدعومة بخبرة حقيقية.',
      story_ch1_b3: 'بعد أكثر من 22 عاماً، أصبح جهروم الخيار الأول لأصحاب البيك آب في الإمارات الذين لا يقبلون التنازل.',
      story_ch2_title: 'البيئة',
      story_ch2_h2_l1: 'مُصمَّم لـ',
      story_ch2_h2_l2: 'تضاريس',
      story_ch2_h2_l3: 'الإمارات.',
      story_ch2_b1: 'صيف يبلغ 48 درجة. رمال في كل مكان. أشعة فوق بنفسجية تدمر الطلاءات الرخيصة في أشهر. الإمارات من أقسى بيئات العالم على إكسسوارات الشاحنات — ومعظم المتاجر تتجاهل ذلك.',
      story_ch2_b2: 'نحن لا نتجاهله. كل منتج في جهروم اختُبر في هذا المناخ — ليس في مختبر، بل في حرارة الشارقة الحقيقية. أغطية صندوق تصدّ الغبار. حماية طلاء لا تصفر. عزل حراري يعمل فعلاً.',
      story_ch2_b3: 'إذا لم يتحمّل سنة كاملة في الإمارات، فلن تجده في صالة العرض لدينا. نقطة.',
      story_ch3_title: 'المنتجات',
      story_ch3_h2_l1: 'ما',
      story_ch3_h2_l2: 'نقدّمه',
      story_ch3_h2_l3: 'فعلاً.',
      story_ch3_b1: 'رام TRX. F-150 رابتور. GMC سييرا دينالي. جهّزناها جميعاً. جهروم متخصص في شاحنات البيك آب الأمريكية — الشاحنات التي يختارها أهل الإمارات حين يرفضون التنازل.',
      story_ch3_b2: 'أغطية صندوق — من الطيّ الثلاثي إلى الأغطية الصلبة القابلة للسحب. تعديلات خارجية — حواجز أمامية، درجات جانبية، رفوف سقف. حماية — طلاء PPF ذاتي الإصلاح. تفصيل داخلي — مقاعد وأرضيات جلدية بأي لون تختار.',
      story_ch3_b3: 'ولأننا نستورد مباشرة من المصنّعين، تبقى أسعارنا تنافسية دون المساس بالجودة. هذا هو الوعد الذي قطعه هادي حين فتح الأبواب — ووعد جهروم يُحفَظ كل يوم.',
      story_ch3_cta: 'تصفّح المنتجات',
      val1_title: 'تركيب دقيق',
      val1_body: 'كل إكسسوار مختار خصيصاً لشاحنات البيك آب الأمريكية. نعرف كل موديل وكل مواصفة. تركيب مثالي في كل مرة.',
      val2_title: 'أسعار عادلة',
      val2_body: 'تعاملنا المباشر مع الموردين يُلغي الوسيط. جودة عالية بأسعار تجعل الاختيار سهلاً.',
      val3_title: 'تركيب احترافي',
      val3_body: 'نحن لا نبيع فقط — بل نُركِّب. كل منتج تُثبِّته أيدي فريقنا الفني بمعايير المصنع.',
      val4_title: 'مُختبَر إماراتياً',
      val4_body: 'أكثر من 22 عاماً من الصحراء والحرارة والرمال اختبرت كل منتج نعرضه. إن وجدته عندنا، فقد أثبت جدارته.',
      val5_title: 'خبرة حقيقية',
      val5_body: 'لا تعرف ماذا تحتاج؟ تعال وتحدّث معنا — سنوصي بما يناسب شاحنتك وأسلوب قيادتك وميزانيتك.',
      val6_title: 'سمعة بالكلمة',
      val6_body: 'سمعتنا بُنيت بالكامل من زبائن عادوا مرة أخرى، وزبائن أحضروا أصدقاءهم.'
    }
  },
  ur: {
    dir: 'rtl', font: 'Noto Nastaliq Urdu', label: 'اردو',
    t: {
      dir: 'rtl',
      font: 'Noto Nastaliq Urdu',
      label: 'اردو',
      nav_home: 'ہوم',
      nav_products: 'مصنوعات',
      nav_story: 'ہماری کہانی',
      nav_contact: 'رابطہ',
      nav_whatsapp: 'واٹس ایپ',
      pl_step1: 'لوڈ ہو رہا ہے...',
      pl_step2: 'تیاری جاری ہے...',
      pl_step3: 'تیار.',
      pl_sub: 'ریگستانی لوہا — 2004 سے — شارجہ، متحدہ عرب امارات',
      hero_tag: 'شارجہ، متحدہ عرب امارات — صنعتی علاقہ 4 — 2004 میں قائم',
      hero_l0: 'ریگستانی',
      hero_l1: 'لوہا.',
      hero_l2: 'تیار.',
      hero_sub: 'ان ڈرائیوروں کے لیے جو سمجھوتہ نہیں کرتے۔ 22 سال سے زائد تجربہ۔ 500 سے زیادہ گاڑیاں۔ ہر تنصیب شارجہ کے صنعتی علاقہ 4 میں ہاتھ سے کی جاتی ہے۔',
      hero_btn_products: 'مصنوعات دیکھیں',
      hero_btn_story: 'ہماری کہانی',
      stat_years: 'سال کا تجربہ',
      stat_rating: 'گوگل ریٹنگ',
      stat_trucks: 'گاڑیاں تیار',
      scroll_lbl: 'اسکرول کریں',
      tick1: 'بیڈ کور',
      tick2: 'خارجی تبدیلیاں',
      tick3: 'آڈیو سسٹم',
      tick4: 'پینٹ پروٹیکشن',
      tick5: 'اپہولسٹری',
      tick6: '4.7★ گوگل ریٹنگ',
      tick7: 'شارجہ، متحدہ عرب امارات',
      ts_tag: 'مصنوعات کا مظاہرہ',
      ts_sub: 'اسکرول کریں',
      ts_loading: 'لوڈ ہو رہا ہے',
      ts_p0_title: 'بنیادی تیاری',
      ts_p0_desc: 'ہر گاڑی بنیاد سے شروع ہوتی ہے — ہم جائزہ لیتے ہیں، منصوبہ بناتے ہیں، اور ہر اضافہ احتیاط سے چنتے ہیں۔ کوئی چیز بلا مقصد نہیں لگاتے۔',
      ts_p0_hint: '↓ اسکرول جاری رکھیں',
      ts_p1_title: 'مکمل سفاری سیٹ اپ',
      ts_p1_desc: 'روشنیاں، اضافے، مکمل کارکردگی۔ یہ ہے جہروم کا مکمل علاج — ہر بیرونی تبدیلی درستی سے، ہر روشنی سیٹ۔ متحدہ عرب امارات کے ریگستان اور اس سے آگے کے لیے۔',
      ts_p1_note: 'خارجی تعمیرات 8,000 درہم سے شروع',
      ts_p2_title: 'بجلی کی سائیڈ اسٹیپ',
      ts_p2_desc: 'بجلی کی سیڑھیاں جو دروازہ کھولتے ہی نکل آتی ہیں۔ گاڑی کی دہلیز پر درستی سے نصب، بند ہونے پر چھپی، استعمال میں مضبوط۔',
      ts_p2_note: 'سائیڈ اسٹیپ 2,200 درہم سے شروع',
      ts_p3_title: 'ٹرائی فولڈ بیڈ کور',
      ts_p3_desc: 'سخت تین حصوں والے کور جو بیڈ کو محفوظ رکھتے ہیں۔ واٹر پروف، کم اونچائی، مضبوط۔ سیکنڈوں میں کھلتے ہیں اور مضبوطی سے بند ہوتے ہیں۔',
      ts_p3_note: 'بیڈ کور 3,400 درہم سے شروع',
      ts_p4_title: 'کسٹم فرنٹ گرل',
      ts_p4_desc: 'کسٹم گرلیں جو گاڑی کا چہرہ بدل دیتی ہیں۔ ہر ایک اصل معیار پر نصب — بغیر سوراخ، بغیر خلا، بغیر ہلنے کے۔',
      ts_p4_note: 'گرلیں 1,800 درہم سے شروع',
      ts_p5_title: 'مکمل کیٹلاگ دیکھیں',
      ts_p5_desc: 'روف ریک، سنارکل، ونچ، لائٹنگ، PPF، آڈیو — جہروم کی مکمل رینج۔ ہر اضافہ اصلی، ہر تنصیب کی ضمانت۔',
      ts_p5_btn: 'مکمل کیٹلاگ دیکھیں',
      ts_hint_text: 'اسکرول کریں',
      ts_hint_sub: '3D تعاملی مظاہرے کے لیے اسکرول جاری رکھیں',
      booking_h3_l1: 'آپ کی گاڑی.',
      booking_h3_l2: 'آپ کی شرائط.',
      booking_text: 'انتظار کی فہرست نہیں۔ اضافی فروخت نہیں۔ اپنی گاڑی کا ماڈل بتائیں اور ہم بتائیں گے کیا مناسب ہے، کتنا خرچ ہوگا، اور کب تیار ہوگی۔',
      booking_btn_wa: 'واٹس ایپ',
      booking_btn_call: 'کال: 050 300 2898',
      booking_info: 'ہفتہ–جمعرات: صبح 8 تا رات 11، جمعہ: دوپہر 3 تا رات 11',
      story_section_tag: 'ہمارا سفر',
      story_section_h2_l1: 'خواب سے',
      story_section_h2_l2: 'حقیقت تک',
      stage1_tag: 'آغاز — 01 / 04',
      stage1_title: 'بنیاد',
      stage1_text: 'صنعتی علاقہ 4۔ 2004۔ ایک اصول: سنجیدہ گاڑیاں سنجیدہ اضافے مانگتی ہیں۔ باقی سب قابلِ گفتگو ہے۔',
      stage2_tag: 'طریقہ — 02 / 04',
      stage2_title: 'ہنر',
      stage2_text: 'کوئی ٹیمپلیٹ نہیں۔ کوئی جلد بازی نہیں۔ ہر تنصیب دو بار جانچی جاتی ہے۔ آپ کی گاڑی ہماری آخری نہیں — لیکن واحد ہے جو اس وقت اہم ہے۔',
      stage3_tag: 'ثبوت — 03 / 04',
      stage3_title: 'اعتماد',
      stage3_text: '4.7★ مارکیٹنگ سے نہیں آئی۔ 500 سے زیادہ گاڑیوں سے آئی جو امارات کی گرمی میں ابھی بھی فیکٹری جیسی دکھتی ہیں۔ بات پھیلتی ہے۔',
      stage4_tag: 'حال — 04 / 04',
      stage4_title: 'آج',
      stage4_text: 'رام TRX۔ F-150 ریپٹر۔ GMC سیرا ڈینالی۔ سب بنائی ہیں۔ آپ کی گاڑی کا اگلا سفر صنعتی علاقہ 4 سے شروع ہوتا ہے۔',
      reviews_h2_l1: 'گاہک',
      reviews_h2_l2: 'کیا کہتے ہیں.',
      rating_label: 'گوگل ریویوز',
      r1_text: '«شارجہ میں 4x4 اضافوں کے لیے بہترین دکان۔ انہیں اپنی گاڑیاں معلوم ہیں — ٹنڈرا، GMC، رام، F-150۔ قیمتیں منصفانہ اور ٹیم واقعی جانتی ہے۔»',
      r1_name: 'عدنان عادی',
      r1_meta: '6 ماہ پہلے',
      r2_text: '«ریئر ہچ کیریئر اسی دن لگ گئی۔ مناسب قیمتیں، سیدھا کام۔ آف روڈ پارٹس کا اچھا ذخیرہ جو شارجہ میں کہیں نہیں ملے گا۔»',
      r2_name: 'ہشام ارشاد',
      r2_meta: '2 ماہ پہلے',
      r3_text: '«پیشہ ور ٹیم۔ معیاری کام۔ میری گاڑی کی ہر تفصیل اچھی طرح سنبھالی گئی — جلد بازی نہیں، کمی نہیں۔ بہت سفارش کرتا ہوں۔»',
      r3_name: 'محمد ر.',
      r3_meta: '4 ماہ پہلے',
      cs_whatsapp_label: 'واٹس ایپ — تیز ترین جواب',
      cs_whatsapp_val: 'ابھی پیغام بھیجیں',
      cs_call_label: 'براہ راست کال',
      cs_call_val: '050 300 2898',
      cs_visit_label: 'آئیں — بغیر اپوائنٹمنٹ',
      cs_visit_val: 'صنعتی علاقہ 4، شارجہ',
      footer_tag: 'ریگستانی لوہا — طاقت کے لیے تیار',
      footer_copy: '© 2025 جہروم آٹو اکسیسریز، شارجہ',
      contact_hero_tag: 'رابطہ کریں',
      contact_hero_h1_l1: 'آئیں.',
      contact_hero_h1_l2: 'بنائیں.',
      contact_hero_sub: 'اپوائنٹمنٹ کی ضرورت نہیں۔ آئیں، اپنی گاڑی بتائیں، اور دیکھیں ہم کیا کر سکتے ہیں۔',
      contact_btn_wa: 'واٹس ایپ پر میسج',
      contact_btn_call: 'کال: 050 300 2898',
      contact_email: 'h_jahrom@yahoo.com',
      contact_social_title: 'کام دیکھیں۔ فالو کریں۔',
      contact_instagram: 'انسٹاگرام',
      contact_youtube: 'یوٹیوب',
      contact_tiktok: 'ٹک ٹاک',
      story_page_hero_sub: 'پختہ ہنر۔ امارات کا ریگستان۔ 22 سال سے زیادہ شارجہ میں بہترین پک اپ ٹرک تیار کرنے کا تجربہ۔',
      story_ch1_title: 'آغاز',
      story_ch1_h2_l1: 'شارجہ میں',
      story_ch1_h2_l2: 'تعمیر.',
      story_ch1_h2_l3: 'لوہے میں',
      story_ch1_h2_l4: 'جڑیں.',
      story_ch1_b1: 'دو دہائیوں سے زائد قبل شارجہ کے قلب میں قائم، جہروم ایک یقین پر کھڑا ہوا: ہر گاڑی پیشہ ورانہ توجہ اور درست تنصیب کی مستحق ہے۔ جو ایک خصوصی ورکشاپ سے شروع ہوا وہ آج متحدہ عرب امارات میں پک اپ ٹرک اضافوں کی سب سے قابل اعتماد منزل بن گئی ہے۔',
      story_ch1_b2: 'جب ہادی نے شارجہ کے صنعتی علاقہ 4 میں دکان کھولی، تو وہ تفصیل سے محبت ساتھ لائے۔ وہ جانتے تھے سنجیدہ ٹرک مالکان کو کیا چاہیے — محض پرزے نہیں، بلکہ اضافے جو واقعی گاڑی کو بہتر بنائیں۔ سوچ کر چنے گئے، درستی سے لگائے گئے، حقیقی علم سے پشت پناہ کیے گئے۔',
      story_ch1_b3: '22 سال سے زائد گزرنے کے بعد، جہروم پورے متحدہ عرب امارات میں پک اپ ٹرک مالکان کی پہلی پسند بن گئی ہے جو سمجھوتہ سے انکاری ہیں۔',
      story_ch2_title: 'ماحول',
      story_ch2_h2_l1: 'امارات کی',
      story_ch2_h2_l2: 'زمین',
      story_ch2_h2_l3: 'کے لیے.',
      story_ch2_b1: '48 ڈگری گرمی۔ ہر جگہ ریت۔ الٹراوائلٹ شعاعیں جو سستے رنگ مہینوں میں برباد کر دیتی ہیں۔ متحدہ عرب امارات ٹرک اضافوں کے لیے دنیا کے سب سے سخت ماحول میں سے ہے — اور زیادہ تر دکانیں یہ نظر انداز کرتی ہیں۔',
      story_ch2_b2: 'ہم نہیں کرتے۔ جہروم کی ہر مصنوعات اسی آب و ہوا میں آزمائی گئی ہے — لیب میں نہیں، شارجہ کی اصل گرمی میں۔ بیڈ کور جو صحرائی دھول روکتے ہیں۔ PPF جو پیلا نہیں ہوتا۔ حرارت کا تحفظ جو کام کرتا ہے۔',
      story_ch2_b3: 'اگر یہ متحدہ عرب امارات کا پورا سال نہیں جھیل سکتی، تو ہمارے شوروم میں جگہ نہیں ملے گی۔ بس۔',
      story_ch3_title: 'مصنوعات',
      story_ch3_h2_l1: 'ہم',
      story_ch3_h2_l2: 'اصل میں',
      story_ch3_h2_l3: 'کیا کرتے ہیں.',
      story_ch3_b1: 'رام TRX۔ F-150 ریپٹر۔ GMC سیرا ڈینالی۔ سب بنائی ہیں۔ جہروم امریکی پک اپ ٹرکوں میں مہارت رکھتا ہے — وہ گاڑیاں جو امارات کے ڈرائیور سمجھوتہ نہ کرنے پر چنتے ہیں۔',
      story_ch3_b2: 'بیڈ کور — سخت قابلِ سحب ڈھکنوں سے لے کر نرم تین حصوں والے کور تک۔ خارجی تعمیرات — بل باز، ریننگ بورڈز، روف ریک۔ تحفظ — خود کو ٹھیک کرنے والا PPF۔ داخلی تفصیل — کسی بھی رنگ میں مکمل چمڑے کی نشستیں اور فرش۔',
      story_ch3_b3: 'اور کیونکہ ہم براہ راست مینوفیکچررز سے خریدتے ہیں، ہماری قیمتیں معیار سے سمجھوتہ کیے بغیر مسابقتی رہتی ہیں۔ یہی وعدہ ہادی نے دروازے کھولتے وقت کیا تھا — اور جہروم یہ وعدہ ہر روز نبھاتا ہے۔',
      story_ch3_cta: 'مصنوعات دیکھیں',
      val1_title: 'درست تنصیب',
      val1_body: 'ہر اضافہ امریکی پک اپ ٹرکوں کے لیے خاص طور پر چنا جاتا ہے۔ ہر ماڈل، ہر سپیسیفیکیشن جانتے ہیں۔ ہر بار بے عیب فٹنگ۔',
      val2_title: 'منصفانہ قیمتیں',
      val2_body: 'سپلائر سے براہ راست تعلق درمیانی آدمی کو ختم کرتا ہے۔ اعلی معیار، مناسب قیمت۔',
      val3_title: 'پیشہ ورانہ تنصیب',
      val3_body: 'ہم صرف بیچتے نہیں — لگاتے بھی ہیں۔ ہر مصنوع ہماری تکنیکی ٹیم کے ہاتھوں فیکٹری معیار پر نصب۔',
      val4_title: 'امارات میں آزمودہ',
      val4_body: '22 سال سے زیادہ کے صحرا، گرمی اور ریت نے ہر مصنوع کو پرکھا ہے۔ اگر ہمارے پاس ہے تو ثابت ہو چکی ہے۔',
      val5_title: 'ماہرانہ رہنمائی',
      val5_body: 'نہیں جانتے کیا چاہیے؟ آئیں اور بات کریں — ہم بتائیں گے آپ کی گاڑی، ڈرائیونگ اور بجٹ کے مطابق کیا بہترین ہے۔',
      val6_title: 'زبانی شہرت',
      val6_body: 'ہماری شہرت مکمل طور پر ان گاہکوں سے بنی ہے جو واپس آئے، اور انہوں نے جو دوستوں کو بھیجا۔'
    }
  },
  fa: {
    dir: 'rtl', font: 'Noto Sans Arabic', label: 'فارسی',
    t: {
      dir: 'rtl',
      font: 'Noto Sans Arabic',
      label: 'فارسی',
      nav_home: 'خانه',
      nav_products: 'محصولات',
      nav_story: 'داستان ما',
      nav_contact: 'تماس',
      nav_whatsapp: 'واتساپ',
      pl_step1: 'در حال بارگذاری...',
      pl_step2: 'لحظه‌ای صبر کنید...',
      pl_step3: 'آماده.',
      pl_sub: 'آهن صحرا — از ۲۰۰۴ — شارجه، امارات',
      hero_tag: 'شارجه، امارات — منطقه صنعتی ۴ — تأسیس ۲۰۰۴',
      hero_l0: 'آهن',
      hero_l1: 'صحرا.',
      hero_l2: 'ساخته شده.',
      hero_sub: 'برای رانندگانی که اهل معامله نیستند. بیش از ۲۲ سال تجربه. بیش از ۵۰۰ خودرو. هر نصب با دست، در منطقه صنعتی ۴ شارجه.',
      hero_btn_products: 'مشاهده محصولات',
      hero_btn_story: 'داستان ما',
      stat_years: 'سال تجربه',
      stat_rating: 'امتیاز گوگل',
      stat_trucks: 'خودرو تجهیز شده',
      scroll_lbl: 'اسکرول کنید',
      tick1: 'روکش صندوق عقب',
      tick2: 'تغییرات بیرونی',
      tick3: 'سیستم صوتی',
      tick4: 'محافظ رنگ',
      tick5: 'روکش داخلی',
      tick6: '4.7★ امتیاز گوگل',
      tick7: 'شارجه، امارات',
      ts_tag: 'معرفی محصولات',
      ts_sub: 'اسکرول کنید',
      ts_loading: 'در حال بارگذاری',
      ts_p0_title: 'ساختار پایه',
      ts_p0_desc: 'هر خودرو از پایه شروع می‌شود — ارزیابی می‌کنیم، برنامه‌ریزی می‌کنیم، و هر لوازم را با دقت انتخاب می‌کنیم. چیزی بی‌دلیل نصب نمی‌شود.',
      ts_p0_hint: '↓ اسکرول را ادامه دهید',
      ts_p1_title: 'ساخت کامل سافاری',
      ts_p1_desc: 'نورپردازی، لوازم، عملکرد کامل. این است درمان کامل جاهروم — هر تغییر بیرونی با دقت نصب، هر نور تنظیم. مناسب برای صحرای امارات و فراتر از آن.',
      ts_p1_note: 'ساخت‌های بیرونی از ۸٬۰۰۰ درهم',
      ts_p2_title: 'پله جانبی برقی',
      ts_p2_desc: 'پله‌های جانبی برقی که با باز شدن در خارج می‌شوند. با دقت روی آستانه خودروی شما نصب، هنگام بسته بودن پنهان، هنگام استفاده محکم.',
      ts_p2_note: 'پله‌های جانبی از ۲٬۲۰۰ درهم',
      ts_p3_title: 'روکش سه‌تایی صندوق عقب',
      ts_p3_desc: 'روکش‌های سخت سه‌تایی که صندوق را ایمن می‌کنند. ضدآب، کم‌ارتفاع، و محکم. در چند ثانیه باز می‌شود و محکم بسته می‌شود.',
      ts_p3_note: 'روکش‌های صندوق از ۳٬۴۰۰ درهم',
      ts_p4_title: 'گریل سفارشی',
      ts_p4_desc: 'گریل‌های سفارشی که چهره خودرو را تغییر می‌دهند. هر کدام با دقت OEM نصب می‌شود — بدون سوراخ‌کاری، بدون فاصله، بدون لرزش.',
      ts_p4_note: 'گریل‌ها از ۱٬۸۰۰ درهم',
      ts_p5_title: 'کاتالوگ کامل را ببینید',
      ts_p5_desc: 'باربند سقف، اسنورکل، وینچ، نورپردازی، PPF، سیستم صوتی — کاتالوگ کامل جاهروم. هر لوازم اصیل، هر نصب تضمین شده.',
      ts_p5_btn: 'مشاهده کاتالوگ کامل',
      ts_hint_text: 'اسکرول برای ساخت',
      ts_hint_sub: 'برای نمایش تعاملی سه‌بعدی اسکرول کنید',
      booking_h3_l1: 'خودروی شما.',
      booking_h3_l2: 'با شرایط شما.',
      booking_text: 'بدون صف انتظار. بدون فروش اجباری. مدل خودروتان را بگویید، ما می‌گوییم چه چیزی مناسب است، چقدر هزینه دارد، و کی آماده می‌شود.',
      booking_btn_wa: 'واتساپ',
      booking_btn_call: 'تماس: 050 300 2898',
      booking_info: 'شنبه–پنجشنبه: ۸ صبح–۱۱ شب، جمعه: ۳ عصر–۱۱ شب',
      story_section_tag: 'مسیر ما',
      story_section_h2_l1: 'از چشم‌انداز تا',
      story_section_h2_l2: 'واقعیت',
      stage1_tag: 'آغاز — ۰۱ / ۰۴',
      stage1_title: 'پایه‌گذاری',
      stage1_text: 'منطقه صنعتی ۴. ۲۰۰۴. یک قانون: خودروهای جدی، تجهیزات جدی می‌خواهند. بقیه قابل مذاکره است.',
      stage2_tag: 'روش — ۰۲ / ۰۴',
      stage2_title: 'هنر',
      stage2_text: 'بدون الگوی از پیش تعیین‌شده. بدون عجله. هر نصب دوبار بررسی می‌شود. خودروی شما آخرین نیست — اما تنها چیزی است که در آن لحظه اهمیت دارد.',
      stage3_tag: 'اثبات — ۰۳ / ۰۴',
      stage3_title: 'اعتماد',
      stage3_text: 'امتیاز ۴.۷★ از بازاریابی نیامد. از بیش از ۵۰۰ خودرویی آمد که در گرمای امارات همچنان مثل روز اول به نظر می‌رسند. شهرت خودش می‌رود.',
      stage4_tag: 'حال — ۰۴ / ۰۴',
      stage4_title: 'امروز',
      stage4_text: 'Ram TRX. F-150 Raptor. GMC Sierra Denali. همه را ساخته‌ایم. فصل بعدی خودروی شما از منطقه صنعتی ۴ شروع می‌شود.',
      reviews_h2_l1: 'مشتریان',
      reviews_h2_l2: 'چه می‌گویند.',
      rating_label: 'نظرات گوگل',
      r1_text: '«بهترین فروشگاه لوازم ۴×۴ در شارجه. گروه را می‌شناسند — تاندرا، GMC، رم، F-150. قیمت‌ها صادقانه و تیم واقعاً می‌داند کارش چیست.»',
      r1_name: 'عدنان عادی',
      r1_meta: '۶ ماه پیش',
      r2_text: '«حامل عقب همان روز نصب شد. قیمت منصفانه، بی‌دردسر. ذخیره خوبی از قطعات آفرود که در جای دیگری در شارجه پیدا نمی‌شود.»',
      r2_name: 'هشام ارشاد',
      r2_meta: '۲ ماه پیش',
      r3_text: '«تیم حرفه‌ای. کار باکیفیت. هر جزئیاتی از خودروم به درستی انجام شد — نه عجله، نه کم‌کاری. کاملاً توصیه می‌کنم.»',
      r3_name: 'محمد ر.',
      r3_meta: '۴ ماه پیش',
      cs_whatsapp_label: 'واتساپ — سریع‌ترین پاسخ',
      cs_whatsapp_val: 'همین الان پیام بدهید',
      cs_call_label: 'تماس مستقیم',
      cs_call_val: '050 300 2898',
      cs_visit_label: 'مراجعه حضوری — بدون وقت قبلی',
      cs_visit_val: 'منطقه صنعتی ۴، شارجه',
      footer_tag: 'آهن صحرا — ساخته برای قدرت',
      footer_copy: '© ۲۰۲۵ جاهروم لوازم خودرو، شارجه',
      contact_hero_tag: 'با ما در تماس باشید',
      contact_hero_h1_l1: 'بیایید.',
      contact_hero_h1_l2: 'بسازیم.',
      contact_hero_sub: 'نیازی به وقت قبلی نیست. بیایید، از خودروتان بگویید، و ما نشان می‌دهیم چه ممکن است.',
      contact_btn_wa: 'پیام در واتساپ',
      contact_btn_call: 'تماس: 050 300 2898',
      contact_email: 'h_jahrom@yahoo.com',
      contact_social_title: 'کارها را ببینید. دنبال کنید.',
      contact_instagram: 'اینستاگرام',
      contact_youtube: 'یوتیوب',
      contact_tiktok: 'تیک‌تاک',
      story_page_hero_sub: 'هنر استادانه. صحرای امارات. بیش از ۲۲ سال ساخت بهترین وانت‌های شارجه.',
      story_ch1_title: 'آغاز',
      story_ch1_h2_l1: 'ساخته در',
      story_ch1_h2_l2: 'شارجه.',
      story_ch1_h2_l3: 'ریشه در',
      story_ch1_h2_l4: 'آهن.',
      story_ch1_b1: 'جاهروم بیش از دو دهه پیش در قلب شارجه تأسیس شد، بر پایه یک باور: هر خودرو شایسته توجه حرفه‌ای و نصب دقیق است. آنچه با یک کارگاه تخصصی آغاز شد، امروز به معتبرترین مقصد لوازم وانت در امارات تبدیل شده است.',
      story_ch1_b2: 'وقتی هادی مغازه را در منطقه صنعتی ۴ شارجه باز کرد، عشق به جزئیات را با خود آورد. می‌دانست صاحبان خودروهای جدی دنبال چه چیزی هستند — نه فقط قطعات، بلکه لوازمی که واقعاً وسیله را ارتقا دهند. با دقت انتخاب شده، با مهارت نصب شده، با دانش واقعی پشتیبانی شده.',
      story_ch1_b3: 'بیش از ۲۲ سال بعد، جاهروم به مقصد اول صاحبان وانت در سراسر امارات تبدیل شده که حاضر به کوتاه آمدن نیستند.',
      story_ch2_title: 'محیط',
      story_ch2_h2_l1: 'ساخته برای',
      story_ch2_h2_l2: 'زمین',
      story_ch2_h2_l3: 'امارات.',
      story_ch2_b1: 'تابستان ۴۸ درجه. شن در هر درزی. اشعه ماورابنفشی که رنگ‌های ارزان را در ماه‌ها خراب می‌کند. امارات یکی از سخت‌ترین محیط‌های جهان برای لوازم خودرو است — و اکثر فروشگاه‌ها این را نادیده می‌گیرند.',
      story_ch2_b2: 'ما نادیده نمی‌گیریم. هر محصول جاهروم در همین آب‌وهوا آزمایش شده — نه در آزمایشگاه، بلکه در گرمای واقعی شارجه. روکش‌هایی که گرد صحرا را دور می‌کنند. PPF که زرد نمی‌شود. عایق حرارتی که واقعاً کار می‌کند.',
      story_ch2_b3: 'اگر نتواند یک سال کامل در امارات دوام بیاورد، جایی در ویترین ما نخواهد داشت. نقطه.',
      story_ch3_title: 'محصولات',
      story_ch3_h2_l1: 'آنچه',
      story_ch3_h2_l2: 'واقعاً',
      story_ch3_h2_l3: 'انجام می‌دهیم.',
      story_ch3_b1: 'Ram TRX. F-150 Raptor. GMC Sierra Denali. همه را ساخته‌ایم. جاهروم در وانت‌های آمریکایی تخصص دارد — همان‌هایی که رانندگان امارات وقتی از معامله امتناع می‌کنند انتخاب می‌کنند.',
      story_ch3_b2: 'روکش صندوق — از سقف‌های سخت کشویی تا روکش‌های نرم سه‌تایی. تغییرات بیرونی — سپر جلو، پله جانبی، باربند سقف. محافظت — PPF خودترمیم. روکش داخلی — صندلی و کف چرمی کامل به هر رنگی.',
      story_ch3_b3: 'و چون مستقیم از تولیدکنندگان تأمین می‌کنیم، قیمت‌هایمان بدون کوتاه آمدن در کیفیت رقابتی می‌ماند. این همان وعده‌ای است که هادی موقع باز کردن در داد — و جاهروم هر روز به آن وفا می‌کند.',
      story_ch3_cta: 'مشاهده محصولات',
      val1_title: 'نصب دقیق',
      val1_body: 'هر لوازم مخصوص وانت‌های آمریکایی انتخاب می‌شود. هر مدل، هر مشخصه را می‌شناسیم. هر بار نصب بی‌نقص.',
      val2_title: 'قیمت منصفانه',
      val2_body: 'ارتباط مستقیم با تأمین‌کنندگان واسطه را حذف می‌کند. کیفیت بالا با قیمتی که انتخاب را آسان می‌کند.',
      val3_title: 'نصب حرفه‌ای',
      val3_body: 'فقط نمی‌فروشیم — نصب هم می‌کنیم. هر محصول توسط تیم فنی ما با استاندارد کارخانه نصب می‌شود.',
      val4_title: 'آزموده در امارات',
      val4_body: 'بیش از ۲۲ سال صحرا، گرما و شن هر محصول را آزموده. اگر پیش ماست، جایگاهش را ثابت کرده.',
      val5_title: 'راهنمایی متخصص',
      val5_body: 'نمی‌دانید چه نیاز دارید؟ بیایید با ما صحبت کنید — دقیقاً می‌گوییم چه چیزی برای خودرو، سبک رانندگی و بودجه‌تان مناسب است.',
      val6_title: 'شهرت کلامی',
      val6_body: 'شهرت ما کاملاً توسط مشتریانی ساخته شده که برگشتند و مشتریانی که دوستانشان را فرستادند.'
    }
  },
  hi: {
    dir: 'ltr', font: 'Noto Sans Devanagari', label: 'हिन्दी',
    t: {
      dir: 'ltr',
      font: 'Noto Sans Devanagari',
      label: 'हिन्दी',
      nav_home: 'होम',
      nav_products: 'उत्पाद',
      nav_story: 'हमारी कहानी',
      nav_contact: 'संपर्क',
      nav_whatsapp: 'व्हाट्सएप',
      pl_step1: 'लोड हो रहा है...',
      pl_step2: 'तैयारी जारी है...',
      pl_step3: 'तैयार.',
      pl_sub: 'रेगिस्तानी लोहा — 2004 से — शारजाह, यूएई',
      hero_tag: 'शारजाह, यूएई — इंडस्ट्रियल एरिया 4 — स्थापना 2004',
      hero_l0: 'रेगिस्तानी',
      hero_l1: 'लोहा.',
      hero_l2: 'निर्मित.',
      hero_sub: 'उन ड्राइवरों के लिए जो समझौता नहीं करते। 22 से अधिक वर्षों का अनुभव। 500+ ट्रक। शारजाह के इंडस्ट्रियल एरिया 4 में हाथ से फिट किए गए।',
      hero_btn_products: 'उत्पाद देखें',
      hero_btn_story: 'हमारी कहानी',
      stat_years: 'वर्षों का अनुभव',
      stat_rating: 'गूगल रेटिंग',
      stat_trucks: 'ट्रक बनाए',
      scroll_lbl: 'स्क्रॉल करें',
      tick1: 'बेड कवर',
      tick2: 'एक्सटीरियर मॉड',
      tick3: 'ऑडियो सिस्टम',
      tick4: 'पेंट प्रोटेक्शन',
      tick5: 'अपहोल्स्ट्री',
      tick6: '4.7★ गूगल रेटिंग',
      tick7: 'शारजाह, यूएई',
      ts_tag: 'उत्पाद प्रदर्शनी',
      ts_sub: 'स्क्रॉल करें',
      ts_loading: 'लोड हो रहा है',
      ts_p0_title: 'बेस बिल्ड',
      ts_p0_desc: 'हर ट्रक आधार से शुरू होता है — हम मूल्यांकन करते हैं, योजना बनाते हैं, और हर एक्सेसरी को ध्यान से चुनते हैं। बिना वजह कुछ नहीं लगता।',
      ts_p0_hint: '↓ स्क्रॉल जारी रखें',
      ts_p1_title: 'पूर्ण सफारी बिल्ड',
      ts_p1_desc: 'लाइटिंग, एक्सेसरीज, पूर्ण प्रदर्शन। यह है जाहरोम का पूरा इलाज — हर बाहरी बदलाव सटीक रूप से, हर लाइट सेट। यूएई के रेगिस्तान और उससे आगे के लिए बनाया गया।',
      ts_p1_note: 'एक्सटीरियर बिल्ड AED 8,000 से शुरू',
      ts_p2_title: 'इलेक्ट्रिक साइड स्टेप',
      ts_p2_desc: 'इलेक्ट्रिक रिट्रेक्टेबल साइड स्टेप जो दरवाज़ा खोलते ही निकल आते हैं। ट्रक के सिल पर सटीक फिट, बंद होने पर छिपे, उपयोग में मज़बूत।',
      ts_p2_note: 'साइड स्टेप AED 2,200 से शुरू',
      ts_p3_title: 'ट्राई-फोल्ड बेड कवर',
      ts_p3_desc: 'हार्ड ट्राई-फोल्ड टोन्यू कवर जो बेड को सुरक्षित रखते हैं। वॉटरप्रूफ, लो-प्रोफाइल, और मज़बूत। सेकंडों में खुलता है और हाइवे स्पीड पर मज़बूती से बंद।',
      ts_p3_note: 'बेड कवर AED 3,400 से शुरू',
      ts_p4_title: 'कस्टम फ्रंट ग्रिल',
      ts_p4_desc: 'कस्टम ग्रिल जो ट्रक का चेहरा बदल देती हैं। हर एक OEM सटीकता से फिट — बिना ड्रिलिंग, बिना गैप, बिना हिलने के।',
      ts_p4_note: 'ग्रिल AED 1,800 से शुरू',
      ts_p5_title: 'पूरा कैटलॉग देखें',
      ts_p5_desc: 'रूफ रैक, स्नॉर्कल, विंच, लाइटिंग, PPF, ऑडियो — जाहरोम की पूरी रेंज। हर एक्सेसरी असली, हर फिटमेंट की गारंटी।',
      ts_p5_btn: 'पूरा कैटलॉग देखें',
      ts_hint_text: 'स्क्रॉल करें',
      ts_hint_sub: '3D इंटरेक्टिव शोकेस के लिए स्क्रॉल करते रहें',
      booking_h3_l1: 'आपका ट्रक.',
      booking_h3_l2: 'आपकी शर्तें.',
      booking_text: 'कोई वेटिंग लिस्ट नहीं। कोई जबरदस्ती नहीं। अपने ट्रक का मॉडल बताएं, हम बताएंगे क्या फिट होगा, कितना खर्च होगा, और कब तैयार होगा।',
      booking_btn_wa: 'व्हाट्सएप',
      booking_btn_call: 'कॉल: 050 300 2898',
      booking_info: 'शनि–गुरु: सुबह 8–रात 11, शुक्र: दोपहर 3–रात 11',
      story_section_tag: 'हमारी यात्रा',
      story_section_h2_l1: 'सपने से',
      story_section_h2_l2: 'हकीकत तक',
      stage1_tag: 'शुरुआत — 01 / 04',
      stage1_title: 'नींव',
      stage1_text: 'इंडस्ट्रियल एरिया 4. 2004. एक नियम: गंभीर ट्रकों को गंभीर गियर चाहिए। बाकी सब बातचीत योग्य है।',
      stage2_tag: 'तरीका — 02 / 04',
      stage2_title: 'कारीगरी',
      stage2_text: 'कोई टेम्पलेट नहीं। कोई जल्दबाज़ी नहीं। हर फिट दो बार जाँचा जाता है। आपका ट्रक हमारा आखिरी नहीं — लेकिन उस पल में एकमात्र मायने रखता है।',
      stage3_tag: 'प्रमाण — 03 / 04',
      stage3_title: 'भरोसा',
      stage3_text: '4.7★ मार्केटिंग से नहीं आई। 500+ ट्रकों से आई जो यूएई की गर्मी में अभी भी फैक्ट्री जैसे दिखते हैं। बात खुद फैलती है।',
      stage4_tag: 'वर्तमान — 04 / 04',
      stage4_title: 'आज',
      stage4_text: 'Ram TRX. F-150 Raptor. GMC Sierra Denali. सभी बनाए हैं। आपके ट्रक का अगला अध्याय इंडस्ट्रियल एरिया 4 से शुरू होता है।',
      reviews_h2_l1: 'ग्राहक क्या',
      reviews_h2_l2: 'कहते हैं.',
      rating_label: 'गूगल रिव्यू',
      r1_text: '«शारजाह में 4x4 एक्सेसरीज़ के लिए सबसे अच्छी दुकान। ये अपने ट्रक जानते हैं — टुंड्रा, GMC, राम, F-150. कीमतें ईमानदार हैं और टीम सच में जानती है।»',
      r1_name: 'अदनान आदी',
      r1_meta: '6 महीने पहले',
      r2_text: '«रियर हिच कैरियर उसी दिन फिट हो गया। उचित कीमतें, सीधा काम। ऑफरोड पार्ट्स का अच्छा स्टॉक जो शारजाह में और कहीं नहीं मिलेगा।»',
      r2_name: 'हिशाम इरशाद',
      r2_meta: '2 महीने पहले',
      r3_text: '«प्रोफेशनल टीम। बढ़िया काम। मेरे ट्रक की हर डिटेल ठीक से संभाली गई — कोई जल्दबाज़ी नहीं, कोई कमी नहीं। पूरी तरह से सिफारिश करता हूँ।»',
      r3_name: 'मोहम्मद आर.',
      r3_meta: '4 महीने पहले',
      cs_whatsapp_label: 'व्हाट्सएप — सबसे तेज़ जवाब',
      cs_whatsapp_val: 'अभी मैसेज करें',
      cs_call_label: 'सीधे कॉल करें',
      cs_call_val: '050 300 2898',
      cs_visit_label: 'आएं — बिना अपॉइंटमेंट',
      cs_visit_val: 'इंडस्ट्रियल एरिया 4, शारजाह',
      footer_tag: 'रेगिस्तानी लोहा — ताकत के लिए बना',
      footer_copy: '© 2025 जाहरोम ऑटो एक्सेसरीज, शारजाह',
      contact_hero_tag: 'संपर्क करें',
      contact_hero_h1_l1: 'आइए.',
      contact_hero_h1_l2: 'बनाएं.',
      contact_hero_sub: 'अपॉइंटमेंट की ज़रूरत नहीं। आएं, अपने ट्रक के बारे में बताएं, और देखें क्या संभव है।',
      contact_btn_wa: 'व्हाट्सएप पर मैसेज',
      contact_btn_call: 'कॉल: 050 300 2898',
      contact_email: 'h_jahrom@yahoo.com',
      contact_social_title: 'काम देखें। फॉलो करें।',
      contact_instagram: 'इंस्टाग्राम',
      contact_youtube: 'यूट्यूब',
      contact_tiktok: 'टिकटॉक',
      story_page_hero_sub: 'कुशल कारीगरी। यूएई का रेगिस्तान। शारजाह में 22 से अधिक वर्षों के बेहतरीन पिकअप ट्रक बनाने का अनुभव।',
      story_ch1_title: 'शुरुआत',
      story_ch1_h2_l1: 'शारजाह में',
      story_ch1_h2_l2: 'निर्मित.',
      story_ch1_h2_l3: 'लोहे में',
      story_ch1_h2_l4: 'जड़ें.',
      story_ch1_b1: 'दो दशकों से भी पहले शारजाह के केंद्र में स्थापित, जाहरोम एक विश्वास पर खड़ा हुआ: हर ट्रक पेशेवर ध्यान और सटीक फिटमेंट का हकदार है। एक विशेष वर्कशॉप से शुरू हुआ जो आज यूएई में पिकअप ट्रक एक्सेसरीज़ का सबसे भरोसेमंद ठिकाना बन गया है।',
      story_ch1_b2: 'जब हादी ने शारजाह के इंडस्ट्रियल एरिया 4 में दुकान खोली, तो वे डिटेल से प्यार साथ लाए। वे जानते थे गंभीर ट्रक मालिक क्या चाहते हैं — सिर्फ पार्ट्स नहीं, बल्कि एक्सेसरीज़ जो वास्तव में गाड़ी को बेहतर बनाएं। सोच-समझकर चुनी, सटीकता से लगाई, असली ज्ञान से समर्थित।',
      story_ch1_b3: '22 से अधिक वर्षों बाद, जाहरोम पूरे यूएई में उन पिकअप ट्रक मालिकों की पहली पसंद बन गया है जो समझौता नहीं करते।',
      story_ch2_title: 'वातावरण',
      story_ch2_h2_l1: 'यूएई की',
      story_ch2_h2_l2: 'ज़मीन',
      story_ch2_h2_l3: 'के लिए.',
      story_ch2_b1: '48°C गर्मी। हर जगह रेत। पराबैंगनी किरणें जो सस्ते कोटिंग को महीनों में बर्बाद कर देती हैं। यूएई ट्रक एक्सेसरीज़ के लिए दुनिया के सबसे कठिन वातावरणों में से एक है — और ज़्यादातर दुकानें इसे नज़रअंदाज़ करती हैं।',
      story_ch2_b2: 'हम नहीं करते। जाहरोम का हर उत्पाद इसी जलवायु में परखा गया है — लैब में नहीं, शारजाह की असली गर्मी में। बेड कवर जो रेगिस्तानी धूल रोकते हैं। PPF जो पीला नहीं होता। थर्मल इंसुलेशन जो वास्तव में काम करता है।',
      story_ch2_b3: 'अगर यह यूएई का एक पूरा साल नहीं झेल सकता, तो हमारे शोरूम में जगह नहीं मिलेगी। बस।',
      story_ch3_title: 'उत्पाद',
      story_ch3_h2_l1: 'हम',
      story_ch3_h2_l2: 'वास्तव में',
      story_ch3_h2_l3: 'क्या करते हैं.',
      story_ch3_b1: 'Ram TRX. F-150 Raptor. GMC Sierra Denali. सभी बनाए हैं। जाहरोम अमेरिकी पिकअप ट्रकों में माहिर है — वे ट्रक जो यूएई के ड्राइवर समझौता न करने पर चुनते हैं।',
      story_ch3_b2: 'बेड कवर — रिट्रेक्टेबल हार्डटॉप से लेकर सॉफ्ट ट्राई-फोल्ड तक। एक्सटीरियर — बुल बार, रनिंग बोर्ड, रूफ रैक। प्रोटेक्शन — सेल्फ-हीलिंग PPF। इंटीरियर — किसी भी रंग में पूरी चमड़े की सीट और फर्श।',
      story_ch3_b3: 'और क्योंकि हम सीधे निर्माताओं से खरीदते हैं, हमारी कीमतें गुणवत्ता से समझौता किए बिना प्रतिस्पर्धी रहती हैं। यही वादा हादी ने दरवाज़े खोलते समय किया था — और जाहरोम यह वादा हर रोज़ निभाता है।',
      story_ch3_cta: 'उत्पाद देखें',
      val1_title: 'सटीक फिटमेंट',
      val1_body: 'हर एक्सेसरी अमेरिकी पिकअप ट्रकों के लिए खास चुनी जाती है। हर मॉडल, हर स्पेसिफिकेशन जानते हैं। हर बार परफेक्ट फिट।',
      val2_title: 'उचित कीमत',
      val2_body: 'सप्लायर से सीधा संबंध बिचौलिए को हटाता है। बेहतरीन गुणवत्ता, ऐसी कीमत जो चुनाव आसान बनाए।',
      val3_title: 'प्रोफेशनल इंस्टॉलेशन',
      val3_body: 'हम सिर्फ बेचते नहीं — लगाते भी हैं। हर उत्पाद हमारी टेक्निकल टीम द्वारा फैक्ट्री स्टैंडर्ड पर इंस्टॉल।',
      val4_title: 'यूएई में परखा',
      val4_body: '22 से अधिक वर्षों के रेगिस्तान, गर्मी और रेत ने हर उत्पाद को परखा है। अगर हमारे पास है, तो साबित हो चुका है।',
      val5_title: 'विशेषज्ञ सलाह',
      val5_body: 'नहीं जानते क्या चाहिए? आएं और हमसे बात करें — हम बताएंगे आपके ट्रक, ड्राइविंग और बजट के लिए क्या सबसे बेहतर है।',
      val6_title: 'मुँह से मुँह',
      val6_body: 'हमारी प्रतिष्ठा पूरी तरह से उन ग्राहकों से बनी है जो वापस आए, और जिन्होंने दोस्तों को भेजा।'
    }
  }
};

// ─── Font loader ───────────────────────────────────────────────────────────────
function juhrumLoadFont(fontName) {
  if (!fontName) return;
  const id = 'juhrum-lang-font';
  let el = document.getElementById(id);
  if (!el) { el = document.createElement('style'); el.id = id; document.head.appendChild(el); }
  const map = {
    'Noto Sans Arabic': 'https://fonts.googleapis.com/css2?family=Noto+Sans+Arabic:wght@300;400;600&display=swap',
    'Noto Nastaliq Urdu': 'https://fonts.googleapis.com/css2?family=Noto+Nastaliq+Urdu:wght@400;700&display=swap',
    'Noto Sans Devanagari': 'https://fonts.googleapis.com/css2?family=Noto+Sans+Devanagari:wght@300;400;600&display=swap',
  };
  const url = map[fontName];
  if (!url) return;
  el.textContent = `@import url('${url}'); [data-lang-active] { font-family: '${fontName}', sans-serif !important; }`;
}

// ─── Core apply function ────────────────────────────────────────────────────────
function juhrumApplyLang(code) {
  const lang = JUHRUM_LANGS[code];
  if (!lang) return;

  localStorage.setItem('juhrum-lang', code);
  document.documentElement.setAttribute('lang', code);
  document.documentElement.setAttribute('dir', lang.dir);
  document.documentElement.setAttribute('data-lang-active', code);

  // RTL body class for layout adjustments
  document.body.classList.toggle('rtl', lang.dir === 'rtl');

  // Load font
  juhrumLoadFont(lang.font);

  // Apply translations
  const t = lang.t;
  document.querySelectorAll('[data-i18n]').forEach(function(el) {
    const key = el.getAttribute('data-i18n');
    if (t[key] !== undefined) {
      // Preserve inner HTML tags (e.g. <strong>, <em>, <br>)
      if (el.innerHTML.includes('<') && !el.innerHTML.includes('data-i18n')) {
        el.innerHTML = t[key];
      } else {
        el.textContent = t[key];
      }
    }
  });

  // Handle placeholder translations (inputs)
  document.querySelectorAll('[data-i18n-placeholder]').forEach(function(el) {
    const key = el.getAttribute('data-i18n-placeholder');
    if (t[key] !== undefined) el.setAttribute('placeholder', t[key]);
  });

  // Sync dropdown UI if present
  var menu = document.getElementById('langDropMenu');
  var label = document.getElementById('langDropLabel');
  if (menu && label) {
    menu.querySelectorAll('.lang-drop-item').forEach(function(item) {
      const isActive = item.getAttribute('data-lang') === code;
      item.classList.toggle('active', isActive);
      if (isActive) label.textContent = lang.label;
    });
  }
}

// ─── Init ───────────────────────────────────────────────────────────────────────
function juhrumInitLang() {
  const saved = localStorage.getItem('juhrum-lang') || 'en';
  juhrumApplyLang(saved);
}

window.juhrumApplyLang = juhrumApplyLang;
window.juhrumInitLang  = juhrumInitLang;
window.JUHRUM_LANGS    = JUHRUM_LANGS;

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', juhrumInitLang);
} else {
  juhrumInitLang();
}
